const state={page:'dashboard',user:{id:'preview-user',first_name:'User'},balance:0,pending:0,lifetime:0,referrals:0,hbc:0,tasks:[],events:[],notifications:[],history:[],friends:[],isAdmin:false,settings:{},community:{},leaderboard:[],lbType:'earners',lbPeriod:'all',activityType:'Earnings',activityPeriod:'All',withdrawals:[],ads:{enabled:false},ai:[],admin:{tab:'overview',userSearch:'',taskSearch:'',proofSearch:'',proofSort:'newest',selectedProofs:[]}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>`$${Number(n||0).toFixed(2)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function tgId(){return String(window.Telegram?.WebApp?.initDataUnsafe?.user?.id||state.user.id||'preview-user')}
async function api(url,opt={}){const tg=window.Telegram?.WebApp;const headers={'X-Telegram-Init-Data':tg?.initData||'',...(opt.headers||{})};let body=opt.body;if(body&&!(body instanceof FormData)&&typeof body!=='string'){headers['Content-Type']='application/json';body=JSON.stringify(body)}const r=await fetch(url,{...opt,headers,body});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
async function sync(){
 const u=window.Telegram?.WebApp?.initDataUnsafe?.user;if(!u?.id)return;
 const d=await api(`/api/bootstrap?telegramId=${encodeURIComponent(u.id)}&username=${encodeURIComponent(u.username||'')}&firstName=${encodeURIComponent(u.first_name||'')}&referralCode=${encodeURIComponent(window.Telegram.WebApp.initDataUnsafe?.start_param||'')}`);
 Object.assign(state,{user:d.user||state.user,tasks:d.tasks||[],balance:+(d.user?.balance||0),pending:+(d.user?.pending_balance||0),lifetime:+(d.user?.lifetime_earnings||0),referrals:+(d.user?.referral_earnings||0),hbc:+(d.user?.hillscoin||0),isAdmin:!!d.admin,events:d.events||[],notifications:d.notifications||[],settings:d.settings||{}});
 try{const p=await api(`/api/profile/details?telegramId=${u.id}`);state.history=p.history||[];state.withdrawals=p.withdrawals||[];state.friends=p.friends||[];state.notifications=(p.notifications||[]).map(n=>({title:n.title,body:n.message,time:n.created_at,unread:!n.read_at}));}catch{}
 try{state.settings=(await api('/api/settings')).settings||state.settings}catch{}
 try{state.ads=(await api('/api/ads')).ads||state.ads}catch{}
 if(state.isAdmin) loadAdmin();
}
function icon(n){return `<span class="i i-${n}"></span>`}
function setPage(p){state.page=p;render();closeMenu()}
function render(){const views={dashboard:dashboardView,earn:earnView,activity:activityView,wallet:walletView,referrals:referralsView,community:communityView,events:eventsView,leaderboard:leaderboardView,notifications:notificationsView,profile:profileView,admin:adminView};$('#main').innerHTML=(views[state.page]||dashboardView)();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page||(state.page==='dashboard'&&b.dataset.page==='dashboard')));$$('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));bind()}
function stat(label,value,ic,go=''){return go?`<button class="card stat-card big-card stat-link" data-go="${go}"><div class="stat-label">${esc(label)}</div><div class="stat-value">${value}</div><span class="stat-icon">${icon(ic)}</span></button>`:`<div class="card stat-card big-card"><div class="stat-label">${esc(label)}</div><div class="stat-value">${value}</div><span class="stat-icon">${icon(ic)}</span></div>`}
function dashboardView(){return `<div class="hero-row"><div><div class="eyebrow">HILLSBYTE</div><div class="hero-name">Welcome back, ${esc(state.user.first_name||'User')}</div><div class="muted">Your earning dashboard</div></div><div class="brand-mark">${esc((state.user.first_name||'U')[0])}</div></div><div class="grid2">${stat('Earnings',money(state.lifetime),'activity','activity')}${stat('Balance',money(state.balance),'wallet','wallet')}${stat('Tasks',state.tasks.length,'spark','earn')}${stat('Referrals',state.friends.length,'users','referrals')}</div><div class="check-card"><div><div class="check-title">${icon('spark')} Daily check-in</div><div class="check-sub">${state.settings.checkin_enabled?'Keep your streak going.':'Available when an admin enables it.'}</div></div><button class="check-btn" id="checkIn">${state.settings.checkin_enabled?'Check in':'Unavailable'}</button></div><div class="quick-title">Quick actions</div><div class="quick-grid">${quick('spark','Earn','earn')}${quick('wallet','Wallet','wallet')}${quick('users','Referrals','referrals')}${quick('activity','Activity','activity')}${quick('community','Community','community')}${quick('calendar','Events','events')}${quick('trophy','Leaderboard','leaderboard')}${quick('user','Profile','profile')}</div>${adSection()}`}
function quick(ic,t,p){return `<button class="quick-item big-action" data-go="${p}"><span class="quick-icon">${icon(ic)}</span><b>${t}</b></button>`}
function adSection(){const on=!!state.ads?.enabled;return `<div class="ad-card"><span class="ad-badge">SPONSORED</span><div class="ad-title">Sponsored ads</div><div class="ad-copy">${on?'Monetag ads are enabled. Open an eligible sponsor ad from HillsByte.':'Sponsored ads are currently turned off by the administrator.'}</div><button class="primary-btn" id="viewAd" ${on?'':'disabled'}>${on?'View sponsored ad':'Ads turned off'}</button></div>`}
function earnView(){const cats=['All','Social','Apps','Web3'];return `<div class="page-head"><h1>Earnings</h1><div class="muted">Complete real tasks and submit proof.</div></div>${adSection()}<div class="toolbar">${cats.map(c=>`<button class="pill ${(!state.cat&&c==='All')||state.cat===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="list">${(state.tasks||[]).filter(t=>!state.cat||state.cat==='All'||String(t.category||'').toLowerCase()===state.cat.toLowerCase()).map(t=>`<div class="list-row large-row"><div><div class="row-title">${esc(t.title)}</div><div class="row-sub">${esc(t.category||'Task')} • ${Number(t.timer_seconds||120)} sec • ${Number(t.remaining_daily??t.daily_slots??0)} slots</div></div><button class="primary-btn" data-task="${t.id}">${money(t.reward)}</button></div>`).join('')||`<div class="empty">${icon('spark')}<strong>No active tasks</strong><p>Admins can publish tasks from the control center.</p></div>`}</div>`}
function activityView(){const days=state.activityPeriod==='7D'?7:state.activityPeriod==='30D'?30:null;const cutoff=days?Date.now()-days*86400000:0;let rows=[];if(state.activityType==='Withdrawals'){rows=(state.withdrawals||[]).map(w=>({title:`Withdrawal • ${w.method||'Payout'}`,status:w.status,created_at:w.created_at,reward:-Number(w.amount||0)}));}else{rows=[...(state.history||[])];if(state.activityType==='Tasks')rows=rows.filter(x=>x.title);if(state.activityType==='Referrals')rows=rows.filter(x=>String(x.kind||'').toLowerCase().includes('referral'));if(state.activityType==='Earnings')rows=rows.filter(x=>Number(x.reward||0)>0||x.status==='approved');}if(days)rows=rows.filter(x=>!x.created_at||new Date(x.created_at).getTime()>=cutoff);return `<div class="page-head"><h1>Activity</h1><div class="muted">Your earnings, balance changes, tasks, referrals and withdrawals.</div></div><div class="grid2">${stat('Earnings',money(state.lifetime),'activity','activity')}${stat('Balance',money(state.balance),'wallet','wallet')}${stat('Tasks',state.user.completed_count||0,'activity','earn')}${stat('Referrals',money(state.referrals),'users','referrals')}${stat('Withdrawals',(state.withdrawals||[]).length,'wallet','wallet')}${stat(state.activityPeriod,'View range','calendar')}</div><div class="toolbar">${['Earnings','Balance','Tasks','Referrals','Withdrawals'].map(x=>`<button class="pill ${state.activityType===x?'active':''}" data-atype="${x}">${x}</button>`).join('')}<span class="spacer"></span>${['7D','30D','All'].map(x=>`<button class="pill ${state.activityPeriod===x?'active':''}" data-aperiod="${x}">${x}</button>`).join('')}</div><div class="list">${rows.map(h=>`<div class="list-row"><div><div class="row-title">${esc(h.title||h.kind||'Account activity')}</div><div class="row-sub">${esc(h.status||h.kind||'recorded')} • ${esc(h.created_at||'')}</div></div><b>${Number(h.reward||0)<0?'−':''}${money(Math.abs(Number(h.reward||0)))}</b></div>`).join('')||`<div class="empty">No ${esc(state.activityType.toLowerCase())} activity for this period.</div>`}</div>`}
function walletView(){const tx=[...(state.history||[]).map(h=>({...h,_kind:'task'})),...(state.withdrawals||[]).map(w=>({title:`Withdrawal • ${w.method||'Payout'}`,status:w.status,created_at:w.created_at,reward:-Number(w.amount||0),_kind:'withdrawal'}))].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')));return `<div class="page-head"><h1>Wallet</h1><div class="muted">Balance, transactions and withdrawals.</div></div><div class="grid2">${stat('Available',money(state.balance),'wallet')}${stat('Pending',money(state.pending),'clock')}${stat('Lifetime',money(state.lifetime),'activity')}${stat('Referral earnings',money(state.referrals),'users')}</div><button class="primary-btn withdraw" id="withdraw">↓ Withdraw</button><div class="quick-title">Withdrawal minimum: ${money(state.settings.min_withdrawal||1)}</div><div class="list">${tx.map(h=>`<div class="list-row"><div><div class="row-title">${esc(h.title||'Task')}</div><div class="row-sub">${esc(h.status||'recorded')} • ${esc(h.created_at||'')}</div></div><b>${Number(h.reward||0)<0?'−':''}${money(Math.abs(Number(h.reward||0)))}</b></div>`).join('')||`<div class="empty">No transactions yet.</div>`}</div>`}
function referralsView(){const link=`https://t.me/HillsByteBot?start=ref_${state.user.referral_code||state.user.id}`;return `<div class="page-head"><h1>Referrals</h1><div class="muted">Invite friends and track your rewards.</div></div><div class="card big-card"><div class="stat-label">Your referral link</div><div class="row-title wrap">${esc(link)}</div><button class="primary-btn" id="copyRef">Copy link</button></div><div class="grid2">${stat('Referrals',state.friends.length,'users')}${stat('Referral earnings',money(state.referrals),'activity')}</div><div class="list">${state.friends.map(f=>`<div class="list-row"><div><div class="row-title">${esc(f.first_name||f.username||'Member')}</div><div class="row-sub">Joined ${esc(f.created_at||'')}</div></div></div>`).join('')||`<div class="empty">No referrals yet.</div>`}</div>`}
async function loadCommunity(){try{state.community=await api('/api/community')}catch{state.community={settings:{community_enabled:true},messages:[]}}}
function communityView(){const c=state.community||{};return `<div class="page-head"><h1>Community</h1><div class="muted">Chat with other HillsByte members.</div></div><div class="community-actions">${c.settings?.channel_url?`<a class="primary-btn" href="${esc(c.settings.channel_url)}" target="_blank">Join channel</a>`:''}${c.settings?.support_url?`<a class="secondary-btn" href="${esc(c.settings.support_url)}" target="_blank">Message support</a>`:''}</div><div class="chat-card"><div id="communityMessages" class="community-messages">${(c.messages||[]).map(m=>`<div class="community-msg"><b>${esc(m.first_name||m.username||'Member')}</b><span>${esc(m.message)}</span><small>${esc(m.created_at||'')}</small></div>`).join('')||'<div class="empty">No messages yet. Start the conversation.</div>'}</div><div class="community-compose"><input id="communityInput" placeholder="Write a message…" maxlength="500"><button class="primary-btn" id="sendCommunity">Send</button></div></div>`}
function eventsView(){return `<div class="page-head"><h1>Events</h1><div class="muted">Upcoming campaigns and community events.</div></div><div class="list">${(state.events||[]).map(e=>`<div class="list-row large-row"><div><div class="row-title">${esc(e.title)}</div><div class="row-sub">${esc(e.description||'HillsByte event')} • ${esc(e.starts_at||'')}</div></div><button class="primary-btn" data-event="${e.id}">View details</button></div>`).join('')||'<div class="empty">No events currently available.</div>'}</div>`}
async function loadLeaderboard(){try{state.leaderboard=(await api(`/api/leaderboard?type=${state.lbType}&period=${state.lbPeriod}`)).rows||[]}catch{state.leaderboard=[]}}
function leaderboardView(){return `<div class="page-head"><h1>Leaderboard</h1><div class="muted">Live rankings from HillsByte activity.</div></div><div class="toolbar">${[['earners','♛ Top Earners'],['referrers','♧ Top Referrers'],['tasks','◷ Most Tasks'],['streak','♨ Longest Streak']].map(([v,t])=>`<button class="pill ${state.lbType===v?'active':''}" data-lb="${v}">${t}</button>`).join('')}</div><div class="toolbar">${['7D','30D','All'].map(x=>{const v=x==='All'?'all':x;return `<button class="pill ${state.lbPeriod===v?'active':''}" data-lbperiod="${v}">${x}</button>`}).join('')}</div><div class="list leaderboard">${state.leaderboard.map((r,i)=>`<div class="list-row"><b>#${i+1} ${esc(r.first_name||r.username||'User')}</b><strong>${state.lbType==='tasks'?Number(r.value||0):state.lbType==='streak'?Number(r.value||0)+' days':money(r.value||0)}</strong></div>`).join('')||'<div class="empty">No rankings yet.</div>'}</div>`}
function notificationsView(){return `<div class="page-head"><h1>Notifications</h1><div class="muted">Account updates and announcements.</div></div><div class="list">${state.notifications.map((n,i)=>`<div class="list-row"><div><div class="row-title">${n.unread?'● ':''}${esc(n.title)}</div><div class="row-sub">${esc(n.body||n.message||'')} • ${esc(n.time||'')}</div></div><button class="pill" data-read="${i}">${n.unread?'Read':'Seen'}</button></div>`).join('')||'<div class="empty">No notifications.</div>'}</div>`}
function profileView(){return `<div class="card profile-card big-card"><div class="avatar">${esc((state.user.first_name||'U')[0])}</div><div><div class="row-title">${esc(`${state.user.first_name||''} ${state.user.last_name||''}`.trim())}</div><div class="row-sub">@${esc(state.user.username||'telegram_user')}</div></div></div><div class="grid2">${stat('Lifetime',money(state.lifetime),'activity')}${stat('Balance',money(state.balance),'wallet')}</div><div class="quick-title">⚙ Settings</div><div class="card settings-card"><label>Language<select id="language"><option ${state.user.language==='English'?'selected':''}>English</option><option>Pidgin English</option><option>French</option><option>Spanish</option><option>Hausa</option><option>Igbo</option><option>Yoruba</option></select></label><label>Currency<select id="currency"><option ${state.user.currency==='USD'?'selected':''}>USD</option><option ${state.user.currency==='NGN'?'selected':''}>NGN</option><option>EUR</option><option>GBP</option></select></label><label>Email<input id="email" value="${esc(state.user.email||'')}" placeholder="Optional email"></label><button class="primary-btn" id="saveProfile">Save settings</button></div><div class="card translator-card"><div class="row-title">Translator</div><div class="row-sub">Translate a message into your selected native language.</div><textarea id="translateText" placeholder="Enter text to translate…"></textarea><button class="secondary-btn" id="translateBtn">Translate</button><div id="translationResult" class="translation-result"></div></div>`}
function adminView(){const a=state.admin;return `<div class="page-head"><h1>Admin Control Center</h1><div class="muted">Manage users, tasks, proofs, withdrawals, events, ads and app settings.</div></div><div class="admin-tabs">${['overview','users','tasks','proofs','withdrawals','events','announcements','ads','settings'].map(t=>`<button class="pill ${a.tab===t?'active':''}" data-atab="${t}">${t}</button>`).join('')}</div>${a.tab==='overview'?adminOverview():a.tab==='users'?adminUsers():a.tab==='tasks'?adminTasks():a.tab==='proofs'?adminProofs():a.tab==='withdrawals'?adminWithdrawals():a.tab==='events'?adminEvents():a.tab==='announcements'?adminAnnouncements():a.tab==='ads'?adminAds():adminSettings()}`}
function adminOverview(){const a=state.admin;return `<div class="grid2">${stat('Total users',(a.totalUsers??a.users?.length??0),'users','admin')}${stat('Active tasks',(a.tasks||[]).filter(x=>x.active).length,'spark')}${stat('Pending proofs',(a.submissions||[]).filter(x=>x.status==='pending').length,'activity')}${stat('Pending withdrawals',(a.withdrawals||[]).filter(x=>x.status==='pending').length,'wallet')}</div><div class="quick-grid"><button class="quick-item big-action" data-atab="users">👥 Users</button><button class="quick-item big-action" data-atab="tasks">✓ Tasks</button><button class="quick-item big-action" data-atab="proofs">▣ Proofs</button><button class="quick-item big-action" data-atab="settings">⚙ Settings</button></div>`}
function adminUsers(){const a=state.admin;const q=(a.userSearch||'').toLowerCase();const rows=(a.users||[]).filter(u=>`${u.first_name} ${u.username} ${u.telegram_id}`.toLowerCase().includes(q));return `<div class="admin-head"><input id="userSearch" value="${esc(a.userSearch||'')}" placeholder="Search users by name, username or Telegram ID"><b>${a.users?.length||0} total users</b></div><div class="list">${rows.map(u=>`<div class="list-row large-row"><div><div class="row-title">${esc(u.first_name||u.username||'User')} ${u.username?`<span class="muted">@${esc(u.username)}</span>`:''}</div><div class="row-sub">ID ${esc(u.telegram_id)} • ${esc(u.status||'active')} • Balance ${money(u.balance)}</div></div><button class="primary-btn" data-user="${u.id}">View profile & activity</button></div>`).join('')||'<div class="empty">No users found.</div>'}</div>`}
function adminTasks(){const a=state.admin;return `<div class="admin-head"><input id="taskSearch" value="${esc(a.taskSearch||'')}" placeholder="Search tasks"><button class="primary-btn" id="newTask">＋ New task</button></div><div class="list">${(a.tasks||[]).filter(t=>String(t.title).toLowerCase().includes((a.taskSearch||'').toLowerCase())).map(t=>`<div class="list-row large-row"><div><div class="row-title">${esc(t.title)}</div><div class="row-sub">${money(t.reward)} • ${t.active?'Active':'Inactive'} • ${esc(t.category||'general')}</div></div><div class="inline-actions"><button class="pill" data-edit-task="${t.id}">Edit</button><button class="pill" data-toggle-task="${t.id}">${t.active?'Deactivate':'Activate'}</button><button class="pill danger" data-delete-task="${t.id}">Delete</button></div></div>`).join('')||'<div class="empty">No tasks.</div>'}</div>`}
function adminProofs(){const a=state.admin;let rows=a.submissions||[];if(a.proofSearch)rows=rows.filter(s=>`${s.first_name} ${s.username} ${s.title}`.toLowerCase().includes(a.proofSearch.toLowerCase()));if(a.proofSort==='oldest')rows=[...rows].reverse();const selected=new Set(a.selectedProofs||[]);return `<div class="admin-head"><input id="proofSearch" value="${esc(a.proofSearch||'')}" placeholder="Search proofs"><select id="proofSort"><option value="newest" ${a.proofSort!=='oldest'?'selected':''}>Newest</option><option value="oldest" ${a.proofSort==='oldest'?'selected':''}>Oldest</option></select><button class="pill" id="selectReviewed">Select reviewed</button><button class="pill" id="clearProofSelection">Clear</button><button class="pill danger" id="deleteReviewed">Delete selected reviewed</button></div><div class="list">${rows.map(s=>`<div class="list-row large-row"><div class="proof-row-left"><input class="proof-check" type="checkbox" data-proof-select="${s.id}" ${selected.has(Number(s.id))?'checked':''}><div><div class="row-title">${esc(s.first_name||s.username||'User')} — ${esc(s.title)}</div><div class="row-sub">${esc(s.status)} • ${esc(s.created_at||'')} • ${money(s.reward)}</div></div></div><div class="inline-actions">${s.screenshots?.[0]?`<button class="pill" data-proof-view="${s.id}">View proof</button>`:''}${s.status==='pending'?`<button class="pill" data-review="${s.id}:approved">Approve</button><button class="pill danger" data-review="${s.id}:rejected">Reject</button>`:''}</div></div>`).join('')||'<div class="empty">No proofs.</div>'}</div>`}
function adminWithdrawals(){return `<div class="list">${(state.admin.withdrawals||[]).map(w=>`<div class="list-row large-row"><div><div class="row-title">${esc(w.username||w.telegram_id)} — ${money(w.amount)}</div><div class="row-sub">${esc(w.method)} • ${esc(w.status)} • ${esc(w.created_at||'')}</div></div>${w.status==='pending'?`<div class="inline-actions"><button class="pill" data-withdraw="${w.id}:approved">Approve</button><button class="pill danger" data-withdraw="${w.id}:rejected">Reject</button></div>`:''}</div>`).join('')||'<div class="empty">No withdrawals.</div>'}</div>`}
function adminEvents(){return `<div class="admin-head"><button class="primary-btn" id="newEvent">＋ New event</button></div><div class="list">${(state.admin.events||[]).map(e=>`<div class="list-row"><div><div class="row-title">${esc(e.title)}</div><div class="row-sub">${esc(e.starts_at)}</div></div><div class="inline-actions"><button class="pill" data-edit-event="${e.id}">Edit</button><button class="pill danger" data-delete-event="${e.id}">Delete</button></div></div>`).join('')||'<div class="empty">No events.</div>'}</div>`}
function adminAnnouncements(){return `<div class="card settings-card"><label>Title<input id="annTitle" placeholder="Announcement title"></label><label>Message<textarea id="annMessage" placeholder="Write the announcement…"></textarea></label><button class="primary-btn" id="sendAnnouncement">Publish announcement</button></div>`}
function adminAds(){const ad=state.admin.ads||{};return `<div class="card big-card"><div class="row-title">Monetag</div><div class="row-sub">Zone 11725898 • ${ad.enabled?'Enabled':'Disabled'}</div><button class="primary-btn" id="saveMonetag">Use Monetag zone 11725898</button><p class="muted">The SDK is installed in the app. Enable it here when you are ready to show ads.</p></div>`}
function adminSettings(){const s=state.settings||{};return `<div class="card settings-card"><label>Minimum withdrawal (USD)<input id="minWithdrawal" type="number" step="0.01" value="${Number(s.min_withdrawal||1)}"></label><label>Check-in enabled <input id="checkinEnabled" type="checkbox" ${s.checkin_enabled?'checked':''}></label><label>Check-in reward <input id="checkinReward" type="number" step="0.01" value="${Number(s.checkin_reward||0.02)}"></label><label>Community enabled <input id="communityEnabled" type="checkbox" ${s.community_enabled!==false?'checked':''}></label><label>Community name<input id="communityName" value="${esc(s.community_name||'HillsByte Community')}"></label><label>Join channel link<input id="channelUrl" value="${esc(s.channel_url||'')}" placeholder="https://t.me/..."></label><label>Default currency<select id="defaultCurrency"><option ${s.default_currency==='USD'?'selected':''}>USD</option><option ${s.default_currency==='NGN'?'selected':''}>NGN</option><option ${s.default_currency==='EUR'?'selected':''}>EUR</option><option ${s.default_currency==='GBP'?'selected':''}>GBP</option></select></label><label>Support link<input id="supportUrl" value="${esc(s.support_url||'')}" placeholder="https://t.me/... or https://t.me/..."></label><button class="primary-btn" id="saveSettings">Save admin settings</button></div>`}
async function loadAdmin(){if(!state.isAdmin)return;try{const r=await Promise.all([api('/api/admin/users'),api('/api/admin/users/count'),api('/api/admin/tasks'),api('/api/admin/submissions'),api('/api/admin/withdrawals'),api('/api/admin/events'),api('/api/admin/ads'),api('/api/admin/broadcasts')]);state.admin.users=r[0].users||[];state.admin.totalUsers=Number(r[1]?.count||state.admin.users.length);state.admin.tasks=r[2].tasks||[];state.admin.submissions=r[3].submissions||[];state.admin.withdrawals=r[4].withdrawals||[];state.admin.events=r[5].events||[];state.admin.ads=r[6]?.ads||r[6]||{};state.admin.broadcasts=r[7]?.broadcasts||[];state.admin.tab=state.admin.tab||'overview'}catch(e){console.warn(e.message)}}
async function startTask(id){try{const task=state.tasks.find(t=>String(t.id)===String(id));const d=await api(`/api/tasks/${id}/start`,{method:'POST',body:{telegramId:tgId()}});openModal(`<div class="modal-head"><h2>${esc(task.title)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>${esc(task.instructions||task.description||'Complete the task.')}</p>${task.task_url||task.url?`<button class="primary-btn" id="openTask">Open task</button>`:''}<input id="proofFiles" type="file" multiple accept="image/*"><textarea id="proofNote" placeholder="Optional note"></textarea><button class="primary-btn" id="submitProof">Submit proof</button>`);$('#openTask')?.addEventListener('click',()=>window.open(task.task_url||task.url,'_blank'));$('#submitProof').onclick=async()=>{const fd=new FormData();fd.append('telegramId',tgId());fd.append('attemptId',d.attempt.id);fd.append('note',$('#proofNote').value);[...$('#proofFiles').files].slice(0,3).forEach(f=>fd.append('screenshots',f));try{await api('/api/submissions',{method:'POST',body:fd});closeModal();toast('Proof submitted for review');await sync();render()}catch(e){toast(e.message)}}}catch(e){toast(e.message)}}
function taskModal(id=null){const t=id?state.admin.tasks.find(x=>x.id==id):{};openModal(`<div class="modal-head"><h2>${id?'Edit task':'New task'}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="form-grid"><input id="tfTitle" placeholder="Title" value="${esc(t.title||'')}"><textarea id="tfDesc" placeholder="Description">${esc(t.description||'')}</textarea><input id="tfReward" type="number" step="0.01" placeholder="Reward" value="${t.reward??0.05}"><input id="tfCategory" placeholder="Category" value="${esc(t.category||'social')}"><input id="tfSlots" type="number" placeholder="Max slots" value="${t.max_slots??1000}"><input id="tfDaily" type="number" placeholder="Daily slots" value="${t.daily_slots??500}"><input id="tfTimer" type="number" placeholder="Timer seconds" value="${t.timer_seconds??120}"><input id="tfUrl" placeholder="Task URL" value="${esc(t.task_url||t.url||'')}"><textarea id="tfInstructions" placeholder="Instructions">${esc(t.instructions||'')}</textarea><textarea id="tfRequirements" placeholder="Requirements">${esc(t.requirements||'')}</textarea></div><button class="primary-btn" id="saveTask">Save task</button>`);$('#saveTask').onclick=async()=>{const body={title:$('#tfTitle').value,description:$('#tfDesc').value,reward:+$('#tfReward').value,category:$('#tfCategory').value,max_slots:+$('#tfSlots').value,daily_slots:+$('#tfDaily').value,timer_seconds:+$('#tfTimer').value,url:$('#tfUrl').value,instructions:$('#tfInstructions').value,requirements:$('#tfRequirements').value,short_description:$('#tfDesc').value,active:t?.active??1};try{await api(id?`/api/admin/tasks/${id}`:'/api/admin/tasks',{method:id?'PUT':'POST',body});closeModal();await loadAdmin();state.admin.tab='tasks';render();toast('Task saved');}catch(e){toast(e.message)}}}
function eventModal(id=null){const e=id?state.admin.events.find(x=>x.id==id):{};openModal(`<div class="modal-head"><h2>${id?'Edit event':'New event'}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><input id="efTitle" placeholder="Title" value="${esc(e.title||'')}"><textarea id="efDesc" placeholder="Description">${esc(e.description||'')}</textarea><input id="efStart" placeholder="Start time" value="${esc(e.starts_at||'')}"><button class="primary-btn" id="saveEvent">Save</button>`);$('#saveEvent').onclick=async()=>{try{await api(id?`/api/admin/events/${id}`:'/api/admin/events',{method:id?'PUT':'POST',body:{title:$('#efTitle').value,description:$('#efDesc').value,starts_at:$('#efStart').value}});closeModal();await loadAdmin();render();toast('Event saved')}catch(e){toast(e.message)}}}
function userModal(id){openModal('<div class="empty">Loading user profile…</div>');api(`/api/admin/users/${id}/activity`).then(d=>{$('#modalRoot').innerHTML=`<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><div class="modal-head"><h2>${esc(d.user.first_name||d.user.username||'User')}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="grid2">${stat('Balance',money(d.user.balance),'wallet')}${stat('Lifetime',money(d.user.lifetime_earnings),'activity')}${stat('Referrals',money(d.user.referral_earnings),'users')}${stat('Tasks',d.user.tasks_completed||0,'activity')}</div><h3>Activity</h3><div class="list">${d.activity.map(x=>`<div class="list-row"><span>${esc(x.kind)} ${esc(x.title||'')}</span><b>${money(x.amount)}</b></div>`).join('')||'<div class="empty">No activity.</div>'}</div><h3>Proofs</h3><div class="list">${d.submissions.map(x=>`<div class="list-row"><span>${esc(x.title||'Task')} • ${esc(x.status)}</span><span>${esc(x.created_at||'')}</span></div>`).join('')||'<div class="empty">No proofs.</div>'}</div></div></div>`})}
function adminUserSearch(){state.admin.userSearch=$('#userSearch').value;render()}
function bind(){
 $$('[data-go]').forEach(b=>b.onclick=()=>setPage(b.dataset.go));$('#checkIn')?.addEventListener('click',async()=>{try{const d=await api('/api/checkin',{method:'POST',body:{telegramId:tgId()}});toast(d.already?'Already checked in today':`Check-in +${money(d.reward)} • streak ${d.streak}`);await sync();render()}catch(e){toast(e.message)}});
 $$('[data-task]').forEach(b=>b.onclick=()=>startTask(b.dataset.task));$$('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render()});$('#copyRef')?.addEventListener('click',()=>navigator.clipboard?.writeText(`https://t.me/HillsByteBot?start=ref_${state.user.referral_code||state.user.id}`).then(()=>toast('Referral link copied')));
 $('#withdraw')?.addEventListener('click',()=>withdrawModal());$$('[data-read]').forEach(b=>b.onclick=async()=>{try{await api('/api/notifications/read',{method:'POST',body:{telegramId:tgId()}})}catch{};state.notifications.forEach(n=>n.unread=false);render()});
 $$('[data-lb]').forEach(b=>b.onclick=async()=>{state.lbType=b.dataset.lb;await loadLeaderboard();render()});$$('[data-lbperiod]').forEach(b=>b.onclick=async()=>{state.lbPeriod=b.dataset.lbperiod;await loadLeaderboard();render()});$$('[data-atype]').forEach(b=>b.onclick=()=>{state.activityType=b.dataset.atype;render()});$$('[data-aperiod]').forEach(b=>b.onclick=()=>{state.activityPeriod=b.dataset.aperiod;render()});$$('[data-proof-view]').forEach(b=>b.onclick=()=>{const s=(state.admin.submissions||[]).find(x=>String(x.id)===String(b.dataset.proofView));openModal(`<div class=\"modal-head\"><h2>Proof — ${esc(s?.title||'Task')}</h2><button class=\"icon-btn\" onclick=\"closeModal()\">×</button></div>${(s?.screenshots||[]).map(x=>`<img src=\"${esc(x)}\" style=\"width:100%;border-radius:12px;margin:6px 0\">`).join('')||'<p>No proof image available.</p>'}`)});
 if(state.page==='community'&&!state.community.messages)loadCommunity().then(render);
 $('#sendCommunity')?.addEventListener('click',sendCommunity);$('#communityInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendCommunity()});
 $('#viewAd')?.addEventListener('click',viewAd);$('#saveProfile')?.addEventListener('click',async()=>{try{const d=await api('/api/profile',{method:'POST',body:{telegramId:tgId(),language:$('#language').value,currency:$('#currency').value,email:$('#email').value}});state.user=d.user;toast('Profile settings saved');render()}catch(e){toast(e.message)}});
 $('#translateBtn')?.addEventListener('click',async()=>{const text=$('#translateText').value.trim();if(!text)return;const out=$('#translationResult');out.textContent='Translating…';try{const d=await api('/api/assistant',{method:'POST',body:{question:`Translate this into ${state.user.language||'English'} and return only the translation:\n${text}`,telegramId:tgId()}});out.textContent=d.answer||'No translation returned.'}catch(e){out.textContent=e.message}});if(state.page==='leaderboard'&&!state.leaderboard.length)loadLeaderboard().then(render);
 if(state.page==='admin'){bindAdmin()}
}
function bindAdmin(){
 $$('[data-atab]').forEach(b=>b.onclick=()=>{state.admin.tab=b.dataset.atab;render()});$('#userSearch')?.addEventListener('input',adminUserSearch);$('#taskSearch')?.addEventListener('input',()=>{state.admin.taskSearch=$('#taskSearch').value;render()});$('#proofSearch')?.addEventListener('input',()=>{state.admin.proofSearch=$('#proofSearch').value;render()});$('#proofSort')?.addEventListener('change',()=>{state.admin.proofSort=$('#proofSort').value;render()});$('#newTask')?.addEventListener('click',()=>taskModal());$('#newEvent')?.addEventListener('click',()=>eventModal());$('#sendAnnouncement')?.addEventListener('click',async()=>{try{await api('/api/admin/announcements',{method:'POST',body:{title:$('#annTitle').value,message:$('#annMessage').value}});toast('Announcement published');await loadAdmin();render()}catch(e){toast(e.message)}});
 $$('[data-event]').forEach(b=>b.onclick=()=>{const e=(state.events||[]).find(x=>String(x.id)===String(b.dataset.event));if(e)openModal(`<div class="modal-head"><h2>${esc(e.title)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>${esc(e.description||'')}</p><div class="row-sub">Starts: ${esc(e.starts_at||'')}</div>`)});$$('[data-user]').forEach(b=>b.onclick=()=>userModal(b.dataset.user));$$('[data-edit-task]').forEach(b=>b.onclick=()=>taskModal(b.dataset.editTask));$$('[data-toggle-task]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/tasks/${b.dataset.toggleTask}/status`,{method:'POST',body:{active:b.textContent==='Activate'}});await loadAdmin();render()}catch(e){toast(e.message)}});$$('[data-delete-task]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this task?'))return;try{await api(`/api/admin/tasks/${b.dataset.deleteTask}`,{method:'DELETE'});await loadAdmin();render()}catch(e){toast(e.message)}});
 $$('[data-review]').forEach(b=>b.onclick=async()=>{const [id,status]=b.dataset.review.split(':');try{await api(`/api/admin/submissions/${id}`,{method:'POST',body:{status}});await loadAdmin();render();toast('Proof updated')}catch(e){toast(e.message)}});$$('[data-withdraw]').forEach(b=>b.onclick=async()=>{const [id,status]=b.dataset.withdraw.split(':');try{await api(`/api/admin/withdrawals/${id}`,{method:'POST',body:{status}});await loadAdmin();render()}catch(e){toast(e.message)}});$$('[data-edit-event]').forEach(b=>b.onclick=()=>eventModal(b.dataset.editEvent));$$('[data-delete-event]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/events/${b.dataset.deleteEvent}`,{method:'DELETE'});await loadAdmin();render()}catch(e){toast(e.message)}});
 $('#selectReviewed')?.addEventListener('click',()=>{state.admin.selectedProofs=(state.admin.submissions||[]).filter(x=>x.status!=='pending').map(x=>Number(x.id));render()});$('#clearProofSelection')?.addEventListener('click',()=>{state.admin.selectedProofs=[];render()});$$('[data-proof-select]').forEach(c=>c.onchange=()=>{const id=Number(c.dataset.proofSelect);const set=new Set(state.admin.selectedProofs||[]);c.checked?set.add(id):set.delete(id);state.admin.selectedProofs=[...set]});$('#deleteReviewed')?.addEventListener('click',async()=>{const ids=(state.admin.selectedProofs||[]).filter(id=>(state.admin.submissions||[]).some(x=>Number(x.id)===id&&x.status!=='pending'));if(!ids.length){toast('Select reviewed proofs first');return}try{await api('/api/admin/submissions/bulk-delete',{method:'POST',body:{ids}});state.admin.selectedProofs=[];await loadAdmin();render();toast('Reviewed proofs deleted')}catch(e){toast(e.message)}});$('#saveSettings')?.addEventListener('click',saveAdminSettings);$('#saveMonetag')?.addEventListener('click',saveMonetag);
}
async function saveAdminSettings(){try{const d=await api('/api/admin/settings',{method:'PUT',body:{min_withdrawal:+$('#minWithdrawal').value,checkin_enabled:$('#checkinEnabled').checked,checkin_reward:+$('#checkinReward').value,community_enabled:$('#communityEnabled').checked,community_name:$('#communityName').value,channel_url:$('#channelUrl').value,support_url:$('#supportUrl').value,default_currency:$('#defaultCurrency').value}});state.settings=d.settings;toast('Admin settings saved');render()}catch(e){toast(e.message)}}
async function saveMonetag(){try{await api('/api/admin/ads',{method:'PUT',body:{provider:'monetag',unit_id:'11725898',reward_amount:0,daily_limit:5,cooldown:30,enabled:true}});toast('Monetag enabled');await loadAdmin();render()}catch(e){toast(e.message)}}
function withdrawModal(){openModal(`<div class="modal-head"><h2>Withdraw</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>Minimum: ${money(state.settings.min_withdrawal||1)}</p><input id="wMethod" placeholder="Bank or crypto"><textarea id="wDetails" placeholder="Payout details"></textarea><button class="primary-btn" id="submitWithdrawal">Submit withdrawal</button>`);$('#submitWithdrawal').onclick=async()=>{try{await api('/api/withdrawals',{method:'POST',body:{telegramId:tgId(),method:$('#wMethod').value,details:$('#wDetails').value}});closeModal();toast('Withdrawal submitted');await sync();render()}catch(e){toast(e.message)}}}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop" id="modalBackdrop"><div class="modal">${html}</div></div>`;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}}
function closeModal(){$('#modalRoot').innerHTML=''}
async function sendCommunity(){const input=$('#communityInput');if(!input?.value.trim())return;try{await api('/api/community/messages',{method:'POST',body:{telegramId:tgId(),message:input.value.trim()}});input.value='';await loadCommunity();render()}catch(e){toast(e.message)}}
function openAI(){openModal(`<div class="modal-head"><h2>HillsByte AI</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div id="aiMessages" class="chat-messages"><div class="msg ai">Hi! Ask me about tasks, withdrawals, referrals, proofs, your activity or HillsByte settings.</div></div><div class="chat-input"><input id="aiInput" placeholder="Ask HillsByte AI…"><button class="primary-btn" id="aiSend">Send</button></div>`);$('#aiSend').onclick=sendAI;$('#aiInput').onkeydown=e=>{if(e.key==='Enter')sendAI()}}
async function sendAI(){const i=$('#aiInput'),q=i.value.trim();if(!q)return;const box=$('#aiMessages');box.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(q)}</div>`);i.value='';try{const d=await api('/api/assistant',{method:'POST',body:{question:q,telegramId:tgId()}});box.insertAdjacentHTML('beforeend',`<div class="msg ai">${esc(d.answer||'No answer')}</div>`)}catch(e){box.insertAdjacentHTML('beforeend',`<div class="msg ai">${esc(e.message||'AI is unavailable right now.')}</div>`)}}
function viewAd(){if(typeof window.show_11725898==='function'){try{window.show_11725898({type:'inApp',inAppSettings:{frequency:2,capping:0.1,interval:30,timeout:5,everyPage:false}})}catch{toast('Ad provider is unavailable right now')}}else toast('Monetag is not ready yet.');}
function toast(m){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2500)}
function openMenu(){$('#sideMenu').classList.add('open');$('#menuShade').classList.add('open')}function closeMenu(){$('#sideMenu').classList.remove('open');$('#menuShade').classList.remove('open')}
$('#menuBtn').onclick=openMenu;$('#closeMenu').onclick=closeMenu;$('#menuShade').onclick=closeMenu;$('#notifBtn').onclick=()=>setPage('notifications');$('#aiFab').onclick=openAI;$$('.nav-item').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
(async()=>{try{window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand();await sync()}catch(e){console.warn(e.message)}$('#splash').classList.add('hidden');$('#app').classList.remove('hidden');render()})();
