const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor?.('#06100c'); tg.setBackgroundColor?.('#050b08'); }
const initData = tg?.initData || '';
const state = { user:null, data:null, route:'earn', adminTab:'overview', editingTask:null };

const routes = [
  ['earn','spark','Earn'],['activity','chart','Activity'],['wallet','wallet','Wallet'],['referrals','users','Referrals'],
  ['community','users','Community'],['events','calendar','Events'],['leaderboard','trophy','Leaderboard'],['notifications','bell','Notifications'],
  ['profile','user','Profile'],['admin','shield','Admin']
];
const $ = s => document.querySelector(s);
const money = n => `$${Number(n||0).toFixed(2)}`;
const headers = () => initData ? {'x-telegram-init-data':initData} : {};
async function api(url, options={}) {
  options.headers = {...(options.headers||{}), ...headers()};
  if (!(options.body instanceof FormData) && options.body && typeof options.body !== 'string') { options.headers['Content-Type']='application/json'; options.body=JSON.stringify(options.body); }
  const r = await fetch(url, options); const d = await r.json().catch(()=>({}));
  if (!r.ok) throw new Error(d.error || 'Request failed'); return d;
}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function icon(name){return `<span class="icon icon-${name}"></span>`}
function closeDrawer(){ $('#drawer').classList.remove('open'); $('#scrim').classList.remove('show'); }
function renderDrawer(){ $('#drawerNav').innerHTML=routes.map(([id,ic,label])=>`<button data-route="${id}" class="${state.route===id?'active':''}"><span class="drawer-icon">${icon(ic)}</span>${label}</button>`).join(''); }
function setRoute(route){state.route=route;renderDrawer();render();closeDrawer();}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r)setRoute(r.dataset.route)});
$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#scrim').classList.add('show')};
$('#closeDrawer').onclick=closeDrawer; $('#scrim').onclick=closeDrawer; $('#notifBtn').onclick=()=>setRoute('notifications');

function stat(label,value,ic,cls=''){return `<div class="card stat-card"><span class="stat-icon ${cls}">${icon(ic)}</span><div class="stat-label">${label}</div><div class="stat-value">${value}</div></div>`}
function empty(ic,title,sub,action=''){return `<div class="empty"><div class="bigicon">${icon(ic)}</div><b>${title}</b><div class="muted" style="margin:6px 0 12px">${sub}</div>${action?`<button class="btn" onclick="${action}">Find tasks</button>`:''}</div>`}
function quick(ic,label,route,bg=''){return `<button onclick="setRoute('${route}')"><span class="qicon ${bg}">${icon(ic)}</span><span>${label}</span></button>`}
function taskCard(t, clickable=true){return `<div class="card task" ${clickable?`data-task-id="${t.id}"`:''}><div class="task-logo">${t.logo_url?`<img src="${escapeHtml(t.logo_url)}" alt="">`:icon('spark')}</div><div class="task-body"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta">${escapeHtml(t.category||'task')} · ${Number(t.est_minutes||1)} min · ${escapeHtml(t.difficulty||'easy')}</div></div><div class="task-reward">+${money(t.reward)}</div></div>`}
function adSlot(placement='earn'){
  const ad=(state.data?.ads||[]).find(x=>x.placement===placement && x.active);
  if(!ad) return `<div class="ad-box"><div class="ad-tag">Sponsored</div><div class="ad-slot"><div><b>HillsByte</b><div class="muted">Ad placement</div></div></div></div>`;
  return `<div class="ad-box"><div class="ad-tag">Sponsored · ${escapeHtml(ad.provider||'Ad')}</div><div class="ad-slot"><div><b>${escapeHtml(ad.name)}</b><div class="muted">${escapeHtml(ad.provider||'Configured placement')}</div></div></div></div>`;
}
function dashboard(){
  const p=state.data?.profile||state.user||{}, tasks=state.data?.tasks||[];
  const days=Array.from({length:7},(_,i)=>`<div class="day ${i < Math.min(7,Number(p.streak||0)%8) ? 'active':''}">D${i+1}</div>`).join('');
  return `<h1 class="page-title">Welcome back, ${escapeHtml(p.first_name||'there')}</h1><div class="muted">Here's your HillsByte snapshot.</div>
  <div class="grid grid-2" style="margin-top:16px">${stat('Available Balance',money(p.balance),'wallet','green')}${stat('Pending',money(p.pending_balance),'clock')}${stat('Lifetime Earnings',money(p.lifetime_earnings),'chart','amber')}${stat('HillsCoin',`${Number(p.hills_coin||25).toFixed(0)} HBC`,'coin','amber')}</div>
  <div class="card checkin"><div class="checkin-head"><div><div class="checkin-title">Daily check-in</div><div class="muted">Current streak: ${Number(p.streak||0)} day${p.streak==1?'':'s'}</div></div><button class="btn" id="checkinBtn">Check in</button></div><div class="streak">${days}</div></div>
  <div class="section-title">Quick actions</div><div class="quick">${quick('spark','Earn','earn')}${quick('wallet','Wallet','wallet','bluebg')}${quick('users','Referral','referrals','purplebg')}${quick('chart','Activity','activity','amberbg')}${quick('users','Community','community','redbg')}${quick('calendar','Events','events')}${quick('trophy','Leaderboard','leaderboard','purplebg')}${quick('user','Profile','profile')}</div>
  <div class="section-title">Featured tasks</div><div class="grid">${tasks.slice(0,4).map(taskCard).join('')||empty('spark','No tasks yet','Complete your first task to start earning.','setRoute(\'earn\')')}</div>${adSlot('earn')}<button class="assistant-fab" id="assistantFab" aria-label="Assistant">✦</button>`;
}
function earn(){const tasks=state.data?.tasks||[];return `<h1 class="page-title">Earn</h1><div class="muted">Complete tasks and build your HillsByte balance.</div><div class="pill-row" style="margin:16px 0"><span class="pill active">All</span><span class="pill">Social</span><span class="pill">Daily</span><span class="pill">Apps</span><span class="pill">Web3</span></div><div class="grid">${tasks.map(t=>taskCard(t)).join('')||empty('spark','No tasks available','Check back soon for new earning opportunities.')}</div>${adSlot('earn')}`}
function activity(){const a=state.data?.activity||[],p=state.data?.profile||{};return `<h1 class="page-title">Activity</h1><div class="muted">Your HillsByte account activity — not financial trading.</div><div class="grid grid-2" style="margin-top:16px">${stat('Total earned',money(p.lifetime_earnings),'chart')}${stat('Avg daily',money(0),'calendar')}${stat('Best day',money(0),'trophy')}${stat('Tasks completed',p.tasks_completed||0,'spark')}${stat('Referral earnings',money(p.referral_earnings),'users')}${stat('Total withdrawals',money(0),'wallet')}</div><div class="section-title">Earnings</div><div class="chart"><div class="chart-grid"></div><div class="chart-dot"></div><div class="muted" style="position:absolute;left:14px;bottom:9px">HillsByte account activity · Earnings</div></div><div class="section-title">Recent activity</div>${a.length?`<div class="grid">${a.map(x=>`<div class="card"><b>${escapeHtml(x.description||x.type)}</b><div class="muted">${new Date(x.created_at).toLocaleString()} · ${money(x.amount)}</div></div>`).join('')}</div>`:empty('chart','No activity yet','Complete tasks to see your earnings chart grow.')}`}
async function wallet(){const w=await api('/api/wallet').catch(()=>({profile:state.data?.profile,transactions:[],withdrawals:[]}));const p=w.profile||{};return `<h1 class="page-title">Wallet</h1><div class="muted">Your balances, transactions and withdrawals.</div><div class="grid grid-2" style="margin-top:16px">${stat('Available',money(p.balance),'wallet')}${stat('Pending',money(p.pending_balance),'clock')}${stat('Lifetime',money(p.lifetime_earnings),'chart','amber')}${stat('Referral earnings',money(p.referral_earnings),'users')}${stat('Withdrawable',money(p.balance),'download')}${stat('HillsCoin',`${Number(p.hills_coin||25).toFixed(0)} HBC`,'coin','amber')}</div><button class="btn" style="margin-top:14px" onclick="withdrawModal()">Request withdrawal</button><div class="section-title">Transactions</div><div class="grid">${(w.transactions||[]).map(x=>`<div class="card"><b>${escapeHtml(x.description||x.type)}</b><div class="muted">${new Date(x.created_at).toLocaleString()}</div><strong style="float:right;color:${Number(x.amount)>=0?'#32ca8d':'#ef858d'}">${Number(x.amount)>=0?'+':''}${money(x.amount)}</strong></div>`).join('')||empty('wallet','No transactions','Your wallet activity will appear here.')}</div>`}
function referrals(){const p=state.data?.profile||{};return `<h1 class="page-title">Referrals</h1><div class="muted">Invite friends and earn referral rewards.</div><div class="card" style="margin-top:16px"><div class="stat-label">Your referral code</div><div style="font-size:20px;font-weight:850">${escapeHtml(p.referral_code||'HB000000')}</div><button class="btn" style="margin-top:12px" onclick="copyText('${escapeHtml(p.referral_code||'')}')">Copy code</button></div><div class="grid grid-2" style="margin-top:10px">${stat('Referral earnings',money(p.referral_earnings),'users','purple')}${stat('Invited users',0,'users','green')}</div>`}
function community(){return `<h1 class="page-title">Community</h1><div class="muted">Stay connected with HillsByte.</div><div class="grid" style="margin-top:16px"><div class="card"><b>HillsByte Community</b><div class="muted" style="margin-top:4px">Join the official community channel.</div><button class="btn" style="margin-top:12px" onclick="openLink('https://t.me/')">Open community</button></div>${(state.data?.announcements||[]).map(a=>`<div class="card"><b>${escapeHtml(a.title)}</b><div class="muted" style="margin-top:5px">${escapeHtml(a.message)}</div></div>`).join('')}</div>`}
function events(){const es=state.data?.events||[];return `<h1 class="page-title">Events</h1><div class="muted">Upcoming HillsByte events and campaigns.</div><div class="grid" style="margin-top:16px">${es.map(e=>`<div class="card"><b>${escapeHtml(e.title)}</b><div class="muted" style="margin-top:5px">${e.start_at?new Date(e.start_at).toLocaleString():''}</div><p class="muted">${escapeHtml(e.description||'')}</p>${e.cta_url?`<button class="btn" onclick="openLink('${escapeHtml(e.cta_url)}')">${escapeHtml(e.cta_label||'Open')}</button>`:''}</div>`).join('')||empty('calendar','No events yet','New events will appear here.')}</div>`}
async function leaderboard(){const d=await api('/api/leaderboard').catch(()=>({leaderboard:[]}));return `<h1 class="page-title">Leaderboard</h1><div class="muted">See how you rank across HillsByte.</div><div class="pill-row" style="margin:16px 0"><span class="pill active">Top Earners</span><span class="pill">Top Referrers</span><span class="pill">Most Tasks</span><span class="pill">Longest Streak</span></div><div class="grid">${(d.leaderboard||[]).slice(0,20).map((x,i)=>`<div class="card" style="display:flex;align-items:center;gap:12px"><b style="width:25px">#${i+1}</b><div class="avatar" style="width:38px;height:38px;font-size:14px">${escapeHtml((x.first_name||'H').slice(0,1).toUpperCase())}</div><div style="flex:1"><b>${escapeHtml(x.first_name||x.username||'User')}</b><div class="muted">${x.tasks_completed||0} tasks · ${x.streak||0} day streak</div></div><strong style="color:#32ca8d">${money(x.lifetime_earnings)}</strong></div>`).join('')||empty('trophy','No rankings yet','Be the first to climb the leaderboard.')}</div>`}
function notifications(){const ns=state.data?.notifications||[];setTimeout(()=>{$('#notifDot').style.display='none'},0);return `<h1 class="page-title">Notifications</h1><div class="muted">Your latest HillsByte updates.</div><div class="notification-panel" style="margin-top:16px">${ns.map(n=>`<div class="notification ${n.read_at?'':'unread'}"><b>${escapeHtml(n.title)}</b><span>${escapeHtml(n.message)} · ${new Date(n.created_at).toLocaleString()}</span></div>`).join('')||empty('bell','No notifications','You are all caught up.')}</div>`}
function profile(){const p=state.data?.profile||{};return `<div class="card profile-card"><div class="avatar">${escapeHtml((p.first_name||'H').slice(0,1).toUpperCase())}</div><div><b>${escapeHtml([p.first_name,p.last_name].filter(Boolean).join(' ')||'HillsByte User')}</b><div class="muted">${p.username?'@'+escapeHtml(p.username):'Telegram user'}</div><div class="muted">Joined HillsByte</div></div>${p.role==='admin'?'<span class="pill active" style="margin-left:auto">Admin</span>':''}</div><div class="settings"><div class="section-title">Settings</div><div class="card"><div class="settings-row"><span>Display currency</span><b>USD — US Dollar</b></div><div class="settings-row"><span>Language</span><b>English</b></div><div class="settings-row"><span>Notifications</span><b>On</b></div><div class="settings-row"><span>Privacy</span><b>Default</b></div><div class="settings-row"><span>Email</span><b style="color:#2fc889">Connected</b></div></div></div>`}

async function admin(){
  if(state.user?.role!=='admin') return `<h1 class="page-title">Admin</h1>${empty('shield','Admin access required','This area is restricted.')}`;
  return `<div class="admin-head"><span class="icon icon-shield"></span><div class="admin-title">Admin Control Center</div></div><div class="admin-tabs">${adminTabButton('overview','grid','Overview')}${adminTabButton('tasks','tasks','Tasks')}${adminTabButton('proofs','image','Proofs')}${adminTabButton('withdrawals','walletline','Withdrawals')}${adminTabButton('events','calendar','Events')}${adminTabButton('announcements','megaphone','Announcements')}${adminTabButton('ads','spark','Ads')}</div><div id="adminContent"></div>`;
}
function adminTabButton(id,ic,label){return `<button class="${state.adminTab===id?'active':''}" onclick="adminTab('${id}')">${icon(ic)}${label}</button>`}
async function adminTab(tab){state.adminTab=tab;const d=await api('/api/admin');const c=$('#adminContent');if(!c)return;$('.admin-tabs').innerHTML=['overview','tasks','proofs','withdrawals','events','announcements','ads'].map(id=>adminTabButton(id,{overview:'grid',tasks:'tasks',proofs:'image',withdrawals:'walletline',events:'calendar',announcements:'megaphone',ads:'spark'}[id],id[0].toUpperCase()+id.slice(1))).join('');
  if(tab==='overview'){c.innerHTML=`<div class="grid grid-2">${stat('Active tasks',d.tasks.filter(x=>x.active).length,'tasks','green')}${stat('Pending proofs',d.submissions.filter(x=>x.status==='pending').length,'image','amber')}${stat('Pending withdrawals',d.withdrawals.filter(x=>x.status==='pending').length,'walletline','blue')}${stat('Announcements',d.announcements.length,'megaphone','purple')}</div><div class="section-title">Quick admin actions</div><div class="quick"><button onclick="newTaskModal()"><span class="qicon">${icon('tasks')}</span><span>New task</span></button><button onclick="adminTab('proofs')"><span class="qicon">${icon('image')}</span><span>Proofs</span></button><button onclick="adminTab('withdrawals')"><span class="qicon">${icon('walletline')}</span><span>Withdrawals</span></button><button onclick="adminTab('announcements')"><span class="qicon">${icon('megaphone')}</span><span>Announcement</span></button></div>`;return}
  if(tab==='tasks'){c.innerHTML=`<button class="btn admin-new" onclick="newTaskModal()">＋&nbsp; New task</button><div class="admin-list">${d.tasks.map(t=>`<div class="admin-item"><div><div class="admin-item-title">${escapeHtml(t.title)}</div><div class="muted">${escapeHtml(t.category)} · ${money(t.reward)} · ${t.active?'active':'inactive'}</div></div><div class="admin-actions"><button class="btn ghost small" onclick='editTask(${JSON.stringify(t).replace(/'/g,"&#39;")})'>Edit</button><button class="btn danger small" onclick="deleteTask('${t.id}')">${icon('trash')}</button></div></div>`).join('')||empty('tasks','No tasks','Create your first task.')}</div>`;return}
  if(tab==='proofs'){c.innerHTML=`<div class="admin-list">${d.submissions.map(s=>`<div class="admin-item"><div style="min-width:0"><div class="admin-item-title">${escapeHtml(s.tasks?.title||'Task')}</div><div class="muted">User ${escapeHtml(s.telegram_id)} · ${escapeHtml(s.status)} · ${money(s.reward)}</div>${s.proof_url?`<button class="btn ghost small" style="margin-top:8px" onclick="openLink('${escapeHtml(s.proof_url)}')">View proof</button>`:''}</div>${s.status==='pending'?`<div class="admin-actions"><button class="btn small" onclick="reviewProof('${s.id}','approved')">Approve</button><button class="btn danger small" onclick="reviewProof('${s.id}','rejected')">Reject</button></div>`:''}</div>`).join('')||empty('image','No proofs','No proof submissions yet.')}</div>`;return}
  if(tab==='withdrawals'){c.innerHTML=`<div class="admin-list">${d.withdrawals.map(w=>`<div class="admin-item"><div><div class="admin-item-title">${money(w.amount)} · ${escapeHtml(w.method)}</div><div class="muted">${escapeHtml(w.telegram_id)} · ${escapeHtml(w.status)}</div><div class="muted">${escapeHtml(w.destination)}</div></div>${w.status==='pending'?`<div class="admin-actions"><button class="btn small" onclick="reviewWithdrawal('${w.id}','approved')">Approve</button><button class="btn danger small" onclick="reviewWithdrawal('${w.id}','rejected')">Reject</button></div>`:''}</div>`).join('')||empty('walletline','No withdrawals','No withdrawal requests yet.')}</div>`;return}
  if(tab==='events'){c.innerHTML=`<button class="btn admin-new" onclick="newEventModal()">＋&nbsp; New event</button><div class="admin-list">${d.events.map(e=>`<div class="admin-item"><div><div class="admin-item-title">${escapeHtml(e.title)}</div><div class="muted">${e.start_at?new Date(e.start_at).toLocaleString():''}</div></div></div>`).join('')||empty('calendar','No events','Create an event.')}</div>`;return}
  if(tab==='announcements'){c.innerHTML=`<div class="admin-form"><div class="field"><input id="aTitle" placeholder="Title"></div><div class="field"><textarea id="aMsg" placeholder="Message"></textarea></div><label class="check"><input id="aPin" type="checkbox"> Pin</label><div style="margin-top:14px"><button class="btn" onclick="saveAnnouncement()">Publish</button></div></div>`;return}
  if(tab==='ads'){c.innerHTML=`<button class="btn admin-new" onclick="newAdModal()">＋&nbsp; Add ad slot</button><div class="admin-list">${d.ads.map(a=>`<div class="admin-item"><div><div class="admin-item-title">${escapeHtml(a.name)}</div><div class="muted">${escapeHtml(a.provider||'')} · ${escapeHtml(a.placement)} · ${a.active?'active':'inactive'}</div></div></div>`).join('')||empty('spark','No ad slots','Add an ad placement for the earn screen.')}</div>`}
}

function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show');$('#modalCard').innerHTML=''}
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function taskForm(t={}){return `<h3>${t.id?'Edit task':'New task'}</h3><div class="field"><label>Title</label><input id="tTitle" value="${escapeHtml(t.title||'')}"></div><div class="field"><label>Description</label><textarea id="tDesc">${escapeHtml(t.description||'')}</textarea></div><div class="field-row"><div class="field"><label>Reward</label><input id="tReward" type="number" step="0.01" value="${Number(t.reward||0)}"></div><div class="field"><label>Category</label><select id="tCategory"><option ${t.category==='content'?'selected':''}>content</option><option ${t.category==='daily'?'selected':''}>daily</option><option ${t.category==='apps'?'selected':''}>apps</option><option ${t.category==='social'?'selected':''}>social</option><option ${t.category==='web3'?'selected':''}>web3</option></select></div></div><div class="field-row"><div class="field"><label>Estimated minutes</label><input id="tMinutes" type="number" value="${Number(t.est_minutes||2)}"></div><div class="field"><label>Timer seconds</label><input id="tTimer" type="number" value="${Number(t.timer_seconds||120)}"></div></div><div class="field-row"><div class="field"><label>Max slots</label><input id="tSlots" type="number" value="${Number(t.max_slots||1000)}"></div><div class="field"><label>Difficulty</label><select id="tDifficulty"><option ${t.difficulty==='easy'?'selected':''}>easy</option><option ${t.difficulty==='medium'?'selected':''}>medium</option><option ${t.difficulty==='hard'?'selected':''}>hard</option></select></div></div><div class="field"><label>Task URL</label><input id="tUrl" value="${escapeHtml(t.task_url||'')}"></div><div class="field"><label>Logo URL</label><input id="tLogo" value="${escapeHtml(t.logo_url||'')}"></div><div class="field"><label>Instructions</label><textarea id="tInstructions">${escapeHtml(t.instructions||'')}</textarea></div><div class="field"><label>Requirements</label><textarea id="tRequirements">${escapeHtml(t.requirements||'')}</textarea></div><label class="check"><input id="tProof" type="checkbox" ${t.proof_required!==false?'checked':''}> Proof screenshot required</label><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveTask()">Save task</button></div>`}
function newTaskModal(){state.editingTask=null;modal(taskForm())}function editTask(t){state.editingTask=t;modal(taskForm(t))}
async function saveTask(){const body={title:$('#tTitle').value.trim(),description:$('#tDesc').value,reward:Number($('#tReward').value),category:$('#tCategory').value,est_minutes:Number($('#tMinutes').value),difficulty:$('#tDifficulty').value,max_slots:Number($('#tSlots').value),timer_seconds:Number($('#tTimer').value),task_url:$('#tUrl').value.trim()||null,logo_url:$('#tLogo').value.trim()||null,instructions:$('#tInstructions').value,requirements:$('#tRequirements').value,proof_required:$('#tProof').checked};try{await api(state.editingTask?`/api/admin/tasks/${state.editingTask.id}`:'/api/admin/tasks',{method:state.editingTask?'PUT':'POST',body});closeModal();toast('Task saved');await refresh();await adminTab('tasks')}catch(e){toast(e.message)}}
async function deleteTask(id){if(!confirm('Delete this task?'))return;try{await api('/api/admin/tasks/'+id,{method:'DELETE'});toast('Task deleted');await refresh();await adminTab('tasks')}catch(e){toast(e.message)}}
async function reviewProof(id,status){const note=status==='rejected'?prompt('Optional rejection note:')||'':'';try{await api(`/api/admin/submissions/${id}/review`,{method:'POST',body:{status,note}});toast('Proof reviewed');await refresh();await adminTab('proofs')}catch(e){toast(e.message)}}
async function reviewWithdrawal(id,status){const note=status==='rejected'?prompt('Optional rejection note:')||'':'';try{await api(`/api/admin/withdrawals/${id}/review`,{method:'POST',body:{status,note}});toast('Withdrawal reviewed');await refresh();await adminTab('withdrawals')}catch(e){toast(e.message)}}
function newEventModal(){modal(`<h3>New event</h3><div class="field"><label>Title</label><input id="eTitle"></div><div class="field"><label>Description</label><textarea id="eDesc"></textarea></div><div class="field"><label>Banner URL</label><input id="eBanner"></div><div class="field-row"><div class="field"><label>Start</label><input id="eStart" type="datetime-local"></div><div class="field"><label>End</label><input id="eEnd" type="datetime-local"></div></div><div class="field"><label>Reward</label><input id="eReward"></div><div class="field"><label>Rules</label><textarea id="eRules"></textarea></div><div class="field-row"><div class="field"><label>CTA label</label><input id="eCta" value="Open"></div><div class="field"><label>CTA URL</label><input id="eUrl"></div></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveEvent()">Create event</button></div>`)}
async function saveEvent(){try{await api('/api/admin/events',{method:'POST',body:{title:$('#eTitle').value,description:$('#eDesc').value,banner_url:$('#eBanner').value||null,reward:$('#eReward').value,rules:$('#eRules').value,start_at:$('#eStart').value?new Date($('#eStart').value).toISOString():null,end_at:$('#eEnd').value?new Date($('#eEnd').value).toISOString():null,cta_label:$('#eCta').value,cta_url:$('#eUrl').value||null}});closeModal();toast('Event created');await refresh();await adminTab('events')}catch(e){toast(e.message)}}
function newAnnouncementModal(){state.adminTab='announcements';render();}
async function saveAnnouncement(){try{await api('/api/admin/announcements',{method:'POST',body:{title:$('#aTitle').value.trim(),message:$('#aMsg').value.trim(),pinned:$('#aPin').checked}});toast('Announcement published');await refresh();await adminTab('announcements')}catch(e){toast(e.message)}}
function newAdModal(){modal(`<h3>Add ad slot</h3><div class="field"><label>Name</label><input id="adName" placeholder="Earn banner"></div><div class="field"><label>Provider</label><input id="adProvider" placeholder="Your ad provider"></div><div class="field"><label>Placement</label><select id="adPlacement"><option value="earn">Earn</option><option value="dashboard">Dashboard</option><option value="wallet">Wallet</option></select></div><div class="field"><label>Provider reference / code</label><textarea id="adCode" placeholder="Keep provider code/configuration server-side when required."></textarea></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveAd()">Save ad slot</button></div>`)}
async function saveAd(){try{await api('/api/admin/ads',{method:'POST',body:{name:$('#adName').value.trim(),provider:$('#adProvider').value.trim(),placement:$('#adPlacement').value,code:$('#adCode').value,active:true}});closeModal();toast('Ad slot saved');await refresh();await adminTab('ads')}catch(e){toast(e.message)}}
function withdrawModal(){modal(`<h3>Request withdrawal</h3><div class="field"><label>Amount</label><input id="wAmount" type="number" min="0.01" step="0.01"></div><div class="field"><label>Method</label><select id="wMethod"><option>Bank</option><option>USDT</option><option>PayPal</option></select></div><div class="field"><label>Destination</label><input id="wDest" placeholder="Account / wallet / destination"></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="submitWithdrawal()">Submit request</button></div>`)}
async function submitWithdrawal(){try{await api('/api/withdrawals',{method:'POST',body:{amount:Number($('#wAmount').value),method:$('#wMethod').value,destination:$('#wDest').value.trim()}});closeModal();toast('Withdrawal submitted');await refresh()}catch(e){toast(e.message)}}
function taskModal(id){const t=(state.data?.tasks||[]).find(x=>x.id===id);if(!t)return;modal(`<h3>${escapeHtml(t.title)}</h3><div class="muted">${escapeHtml(t.description||'')}</div><div class="card" style="margin-top:12px"><b>Reward</b><strong style="float:right;color:#32ca8d">${money(t.reward)}</strong><p class="muted">${escapeHtml(t.instructions||'Complete the task and submit your proof.')}</p><p class="muted">${escapeHtml(t.requirements||'')}</p></div>${t.task_url?`<button class="btn" style="margin-top:12px" onclick="openLink('${escapeHtml(t.task_url)}')">Open task</button>`:''}<div class="field" style="margin-top:14px"><label>Proof screenshot ${t.proof_required?'(required)':''}</label><input id="proofFile" type="file" accept="image/png,image/jpeg,image/webp"></div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn" onclick="submitTask('${t.id}')">Submit task</button></div>`)}
async function submitTask(id){try{const f=$('#proofFile')?.files?.[0];const fd=new FormData();if(f)fd.append('proof',f);const r=await fetch('/api/tasks/'+id+'/submit',{method:'POST',headers:headers(),body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Submission failed');closeModal();toast('Task submitted for review');await refresh()}catch(e){toast(e.message)}}
function assistant(){modal(`<h3>HillsByte Assistant</h3><div id="chat" class="chat"></div><div class="chat-input"><input id="chatInput" placeholder="Ask about tasks, wallet or referrals"><button class="btn" onclick="sendAssistant()">Send</button></div>`)}
async function sendAssistant(){const input=$('#chatInput'),msg=input.value.trim();if(!msg)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHtml(msg)}</div>`);input.value='';try{const d=await api('/api/assistant',{method:'POST',body:{message:msg}});$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble ai">${escapeHtml(d.reply)}</div>`)}catch(e){$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble ai">${escapeHtml(e.message)}</div>`)}}
function copyText(t){navigator.clipboard?.writeText(t);toast('Copied')};function openLink(u){if(u)window.open(u,'_blank','noopener,noreferrer')}
document.addEventListener('click',e=>{const t=e.target.closest('[data-task-id]');if(t)taskModal(t.dataset.taskId);if(e.target.closest('#checkinBtn'))doCheckin();if(e.target.closest('#assistantFab'))assistant()});
async function doCheckin(){try{const d=await api('/api/checkin',{method:'POST'});toast(d.already?'Already checked in today':`Check-in +${money(d.reward)}`);await refresh()}catch(e){toast(e.message)}}
async function render(){const v=$('#view');try{v.innerHTML=state.route==='earn'?dashboard():state.route==='activity'?activity():state.route==='wallet'?await wallet():state.route==='referrals'?referrals():state.route==='community'?community():state.route==='events'?events():state.route==='leaderboard'?await leaderboard():state.route==='notifications'?notifications():state.route==='profile'?profile():await admin();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));if(state.route==='admin')await adminTab(state.adminTab)}catch(e){v.innerHTML=empty('shield','Something went wrong',e.message)}}
async function refresh(){state.data=await api('/api/dashboard');state.user=state.data.profile||state.user;renderDrawer();await render()}
async function boot(){try{const s=await api('/api/session');state.user=s.user;state.data=await api('/api/dashboard');renderDrawer();await render();if(state.user?.role==='admin')document.body.classList.add('is-admin')}catch(e){$('#view').innerHTML=`<div class="empty"><div class="bigicon">${icon('shield')}</div><b>HillsByte could not start</b><div class="muted">${escapeHtml(e.message)}</div></div>`}finally{setTimeout(()=>$('#splash').classList.add('hide'),650)}}
boot();
