import express from"express";
import path from"path";
import crypto from"crypto";
import{fileURLToPath}from"url";
import{createClient}from"@supabase/supabase-js";

const app=express();app.use(express.json({limit:"1mb"}));
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const URL=process.env.SUPABASE_URL||"";const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||"";
const sb=createClient(URL,KEY,{auth:{persistSession:false}});
const BOT=process.env.BOT_TOKEN||"";const ADMINS=(process.env.ADMIN_TELEGRAM_IDS||"").split(",").map(x=>x.trim()).filter(Boolean);
const CHANNEL=process.env.CHANNEL_USERNAME||"";
const bucket="hillsbyte-proofs";

function auth(req){
 const raw=req.header("X-Telegram-Init-Data")||"";if(!raw||!BOT)throw Error("Open HillsByte from Telegram.");
 const p=new URLSearchParams(raw),hash=p.get("hash");if(!hash)throw Error("Invalid Telegram session.");
 const pairs=[...p.entries()].filter(([k])=>k!=="hash").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");
 const secret=crypto.createHmac("sha256","WebAppData").update(BOT).digest();
 const calc=crypto.createHmac("sha256",secret).update(pairs).digest("hex");
 if(!crypto.timingSafeEqual(Buffer.from(calc),Buffer.from(hash)))throw Error("Telegram authentication failed.");
 const u=JSON.parse(p.get("user")||"{}");if(!u.id)throw Error("Telegram user missing.");return u;
}
async function me(req){
 const u=auth(req);
 let{data:x,error}=await sb.from("users").select("*").eq("telegram_id",String(u.id)).maybeSingle();if(error)throw error;
 const role=ADMINS.includes(String(u.id))?"admin":x?.role;
 if(!x){const referral=(new URLSearchParams(req.header("X-Telegram-Init-Data")||"")).get("start_param")||"";let referred=null;if(referral.startsWith("ref_")){const{data:r}=await sb.from("users").select("id").eq("display_username",referral.slice(4)).maybeSingle();referred=r?.id||null}
  const{data:n,error:e}=await sb.from("users").insert({telegram_id:String(u.id),telegram_username:u.username||null,first_name:u.first_name||"",last_name:u.last_name||"",display_username:u.username||`member_${u.id}`,referred_by:referred}).select("*").single();if(e)throw e;x=n;
 }else if(x.telegram_username!==(u.username||null)||x.first_name!==(u.first_name||"")){await sb.from("users").update({telegram_username:u.username||null,first_name:u.first_name||"",last_name:u.last_name||"",updated_at:new Date().toISOString()}).eq("id",x.id);x={...x,telegram_username:u.username||null,first_name:u.first_name||""}}
 if(role==="admin"&&x.role!=="admin"){await sb.from("users").update({role:"admin"}).eq("id",x.id);x.role="admin"}
 x.checked_today=x.last_checkin_date===new Date().toISOString().slice(0,10);return{x,tg:u};
}
function fail(res,e){res.status(400).json({error:e.message||"Request failed"})}
async function settings(){const{data,error}=await sb.from("settings").select("*").eq("id",true).single();if(error)throw error;return data}
async function isMember(id){if(!BOT||!CHANNEL)return true;try{const r=await fetch(`https://api.telegram.org/bot${BOT}/getChatMember?chat_id=${encodeURIComponent(CHANNEL)}&user_id=${id}`);const d=await r.json();if(!d.ok)return true;return["creator","administrator","member"].includes(d.result.status)||(d.result.status==="restricted"&&d.result.is_member)}catch{return true}}

app.get("/api/bootstrap",async(req,res)=>{try{const{ x,tg}=await me(req);const[st,tasks,events,broadcasts]=await Promise.all([settings(),sb.from("tasks").select("*").eq("active",true).order("created_at",{ascending:false}),sb.from("events").select("*").eq("active",true).order("starts_at"),sb.from("broadcasts").select("*").order("created_at",{ascending:false}).limit(5)]);const member=await isMember(tg.id);res.json({user:x,tasks:tasks.data||[],events:events.data||[],broadcasts:broadcasts.data||[],admin:x.role==="admin",channel_member:member})}catch(e){fail(res,e)}});

app.get("/api/dashboard",async(req,res)=>{try{const{ x}=await me(req);const{data:recent}=await sb.from("activity_events").select("*").eq("user_id",x.id).order("created_at",{ascending:false}).limit(8);res.json({recent:recent||[]})}catch(e){fail(res,e)}});

app.get("/api/tasks",async(req,res)=>{try{const{ x}=await me(req);const{data}=await sb.from("tasks").select("*").eq("active",true).order("created_at",{ascending:false});const today=new Date().toISOString().slice(0,10);const out=[];for(const t of data||[]){const{count}=await sb.from("task_completions").select("id",{count:"exact",head:true}).eq("task_id",t.id);const{count:tc}=await sb.from("task_completions").select("id",{count:"exact",head:true}).eq("task_id",t.id).gte("completed_at",today+"T00:00:00Z");out.push({...t,completed:count||0,today:tc||0})}res.json({tasks:out})}catch(e){fail(res,e)}});

app.post("/api/tasks/:id/start",async(req,res)=>{try{const{ x}=await me(req);if(x.status!=="active")throw Error("Your account is restricted.");const st=await settings();if(Number(x.trust_score)<=Number(st.trust_ad_only_min))return res.json({blockedByTrust:true,message:"Your trust score is 50 or below. Only ad activity is currently available."});if(Number(x.trust_score)<Number(st.trust_event_min)){}const{data:t}=await sb.from("tasks").select("*").eq("id",req.params.id).eq("active",true).single();if(!t)throw Error("Task unavailable.");const expires=new Date(Date.now()+Number(t.timer_seconds||120)*1000).toISOString();const{data:a,error}=await sb.from("task_attempts").insert({task_id:t.id,user_id:x.id,expires_at:expires}).select("*").single();if(error)throw error;res.json({attempt:a,sponsorRequired:t.sponsor_ad_required})}catch(e){fail(res,e)}});

app.post("/api/upload-url",async(req,res)=>{try{const{x}=await me(req);const ext=String(req.body.ext||"jpg").replace(/[^a-z0-9]/gi,"").slice(0,6)||"jpg";const p=`${x.id}/${crypto.randomUUID()}.${ext}`;const{data,error}=await sb.storage.from(bucket).createSignedUploadUrl(p,{upsert:false});if(error)throw error;res.json({url:data.signedUrl,path:p,token:data.token,project:URL})}catch(e){fail(res,e)}});

app.post("/api/submissions",async(req,res)=>{try{const{x}=await me(req);const{attemptId,taskId,proofPaths,note}=req.body;const{data:a}=await sb.from("task_attempts").select("*").eq("id",attemptId).eq("user_id",x.id).single();if(!a||a.task_id!==taskId)throw Error("Invalid task attempt.");if(new Date(a.expires_at)<new Date())throw Error("Task timer expired.");if(!Array.isArray(proofPaths)||!proofPaths.length)throw Error("Proof screenshot required.");const{error:e1}=await sb.from("task_attempts").update({status:"submitted"}).eq("id",a.id);if(e1)throw e1;const{data:s,error}=await sb.from("submissions").insert({attempt_id:a.id,task_id:taskId,user_id:x.id,proof_paths:proofPaths,note:note||"",status:"under_review"}).select("*").single();if(error)throw error;res.json({submission:s})}catch(e){fail(res,e)}});

app.post("/api/ads/complete",async(req,res)=>{try{const{x}=await me(req);await sb.from("ad_views").insert({user_id:x.id,provider:"monetag",zone_id:"11725898",rewarded:true});const st=await settings();const{count}=await sb.from("ad_views").select("id",{count:"exact",head:true}).eq("user_id",x.id);if((count||0)%Number(st.trust_ad_reward_views||10)===0&&count){await sb.from("users").update({trust_score:Math.min(100,Number(x.trust_score)+Number(st.trust_ad_reward||2))}).eq("id",x.id)}res.json({ok:true})}catch(e){fail(res,e)}});

app.get("/api/ads",async(req,res)=>{try{const{x}=await me(req);const{count}=await sb.from("ad_views").select("id",{count:"exact",head:true}).eq("user_id",x.id);res.json({views:count||0})}catch(e){fail(res,e)}});

app.post("/api/checkin",async(req,res)=>{try{const{x}=await me(req);const today=new Date().toISOString().slice(0,10);if(x.last_checkin_date===today)throw Error("Already checked in today.");const st=await settings();const day=Math.min(7,Number(x.current_streak||0)+1);const reward=Number(st.checkin_rewards?.[`D${day}`]||0);await sb.from("checkins").insert({user_id:x.id,day_index:day,checkin_date:today,reward});await sb.from("users").update({current_streak:day,best_streak:Math.max(Number(x.best_streak||0),day),last_checkin_date:today,balance:Number(x.balance)+reward}).eq("id",x.id);res.json({ok:true,reward})}catch(e){fail(res,e)}});

app.get("/api/profile",async(req,res)=>{try{const{x}=await me(req);const[{count:completed},{data:streak},{data:events}]=await Promise.all([sb.from("task_completions").select("id",{count:"exact",head:true}).eq("user_id",x.id),sb.from("checkins").select("checkin_date").eq("user_id",x.id).order("checkin_date",{ascending:false}).limit(30),sb.from("event_participants").select("event:events(*)").eq("user_id",x.id).is("completed_at",null)]);res.json({completed:completed||0,streak:(streak||[]).map(x=>x.checkin_date),events:(events||[]).map(x=>x.event)})}catch(e){fail(res,e)}});

app.post("/api/profile",async(req,res)=>{try{const{x}=await me(req);const name=String(req.body.display_username||"").trim().slice(0,40);if(!name)throw Error("Username is required.");await sb.from("users").update({display_username:name,updated_at:new Date().toISOString()}).eq("id",x.id);res.json({ok:true})}catch(e){fail(res,e)}});

app.get("/api/activity",async(req,res)=>{try{const{x}=await me(req);const{data}=await sb.from("task_completions").select("id,reward,completed_at,task:tasks(title),submission:submissions(status)").eq("user_id",x.id).order("completed_at",{ascending:false}).limit(50);const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);days.push({label:k.slice(5),value:(data||[]).filter(r=>r.completed_at.slice(0,10)===k).reduce((a,b)=>a+Number(b.reward||0),0)})}res.json({chart:days,history:(data||[]).map(r=>({id:r.id,title:r.task?.title||"Task",reward:r.reward,status:r.submission?.status||"approved",created_at:r.completed_at}))})}catch(e){fail(res,e)}});

app.get("/api/wallet",async(req,res)=>{try{res.json({settings:await settings()})}catch(e){fail(res,e)}});

app.post("/api/withdrawals",async(req,res)=>{try{const{x}=await me(req),st=await settings();const amount=Number(x.balance);const method=req.body.method;if(method==="bank"&&amount<Number(st.bank_min_withdrawal))throw Error(`Minimum bank withdrawal is $${st.bank_min_withdrawal}.`);if(method==="crypto"&&amount<Number(st.crypto_min_withdrawal))throw Error(`Minimum crypto withdrawal is $${st.crypto_min_withdrawal}.`);const fee=method==="bank"?amount*Number(st.bank_withdrawal_fee_percent)/100:0;const net=amount-fee;const ngn=method==="bank"?net*Number(st.usd_ngn_rate):null;const{data,error}=await sb.from("withdrawals").insert({user_id:x.id,method,amount_usd:amount,fee_usd:fee,net_usd:net,ngn_rate:method==="bank"?st.usd_ngn_rate:null,ngn_amount:ngn,details:req.body}).select("*").single();if(error)throw error;await sb.from("users").update({balance:0,pending_balance:Number(x.pending_balance)+amount}).eq("id",x.id);res.json({withdrawal:data})}catch(e){fail(res,e)}});

app.get("/api/referrals",async(req,res)=>{try{const{x}=await me(req);const{data}=await sb.from("referrals").select("*").eq("referrer_id",x.id);const code=x.display_username;res.json({code,link:`https://t.me/${process.env.BOT_USERNAME||"HillsByteBot"}?start=ref_${code}`,total:data?.length||0,pending:(data||[]).filter(r=>r.status==="pending").length,commissions:(data||[]).reduce((a,r)=>a+Number(r.commission_usd||0),0)})}catch(e){fail(res,e)}});

app.get("/api/community",async(req,res)=>{try{const{data}=await sb.from("community_posts").select("*,user:users(telegram_username,first_name)").is("deleted_at",null).order("created_at",{ascending:false}).limit(50);for(const p of data||[]){const{data:c}=await sb.from("community_comments").select("*,user:users(telegram_username,first_name)").eq("post_id",p.id).order("created_at");p.comments=c||[]}res.json({posts:data||[]})}catch(e){fail(res,e)}});

app.post("/api/community",async(req,res)=>{try{const{x}=await me(req);const body=String(req.body.body||"").trim();if(!body)throw Error("Write something first.");const st=await settings();const lower=body.toLowerCase();const bad=(st.banned_hash_words||[]).some(w=>lower.includes(String(w).toLowerCase()));if(bad){const cost=.05;const next=Number(x.balance)-cost;await sb.from("users").update({balance:Math.max(0,next),debt:Math.max(0,-next)}).eq("id",x.id);throw Error(next<0?"Blocked phrase detected. $0.05 was added to your debt.":"Blocked phrase detected. $0.05 was deducted and the post was removed.");}const{data,error}=await sb.from("community_posts").insert({user_id:x.id,body}).select("*").single();if(error)throw error;res.json({post:data})}catch(e){fail(res,e)}});

app.post("/api/community/:id/comments",async(req,res)=>{try{const{x}=await me(req);const body=String(req.body.body||"").trim();if(!body)throw Error("Comment is empty.");const{data,error}=await sb.from("community_comments").insert({post_id:req.params.id,user_id:x.id,body}).select("*").single();if(error)throw error;res.json({comment:data})}catch(e){fail(res,e)}});

app.get("/api/events",async(req,res)=>{try{const{data}=await sb.from("events").select("*").eq("active",true).order("starts_at");res.json({events:data||[]})}catch(e){fail(res,e)}});

app.get("/api/leaderboard",async(req,res)=>{try{const{data}=await sb.from("users").select("telegram_id,telegram_username,first_name,display_username,xp").eq("status","active").order("xp",{ascending:false}).limit(20);const out=[];for(const x of data||[]){const{count}=await sb.from("task_completions").select("id",{count:"exact",head:true}).eq("user_id",(await sb.from("users").select("id").eq("telegram_id",x.telegram_id).single()).data.id);out.push({...x,completed:count||0})}res.json({users:out})}catch(e){fail(res,e)}});

app.get("/api/notifications",async(req,res)=>{try{const{x}=await me(req);const{data}=await sb.from("notifications").select("*").eq("user_id",x.id).order("created_at",{ascending:false}).limit(50);res.json({notifications:data||[]})}catch(e){fail(res,e)}});

app.post("/api/redeem",async(req,res)=>{try{const{x}=await me(req);const code=String(req.body.code||"").trim().toUpperCase();const{data:c}=await sb.from("redeem_codes").select("*").eq("code",code).eq("active",true).single();if(!c||c.used_count>=c.capacity)throw Error("Invalid or exhausted redeem code.");const{data:r}=await sb.from("redeem_redemptions").select("*").eq("code_id",c.id).eq("user_id",x.id).maybeSingle();if(r)throw Error("Code already redeemed.");await sb.from("redeem_redemptions").insert({code_id:c.id,user_id:x.id});await sb.from("redeem_codes").update({used_count:c.used_count+1}).eq("id",c.id);await sb.from("users").update({balance:Number(x.balance)+Number(c.amount_usd),hillscoin:Number(x.hillscoin)+Number(c.hillscoin)}).eq("id",x.id);res.json({ok:true})}catch(e){fail(res,e)}});

function adminOnly(req){return me(req).then(({x})=>{if(x.role!=="admin")throw Error("Admin access required.");return x})}
app.get("/api/admin/overview",async(req,res)=>{try{await adminOnly(req);const tables=await Promise.all([sb.from("users").select("id,balance,pending_balance,hillscoin,created_at"),sb.from("task_completions").select("reward"),sb.from("withdrawals").select("amount_usd,fee_usd,status"),sb.from("ad_views").select("id"),sb.from("referrals").select("status"),sb.from("community_posts").select("id"),sb.from("submissions").select("status")]);const[u,c,w,a,r,cp,sub]=tables;const revenue=(c.data||[]).reduce((n,x)=>n+Number(x.reward),0);res.json({revenue,pending_revenue:(u.data||[]).reduce((n,x)=>n+Number(x.pending_balance),0),tasks_completed:c.data?.length||0,ads_watched:a.data?.length||0,users:u.data?.length||0,pending_referrals:(r.data||[]).filter(x=>x.status==="pending").length,pending_withdrawals:(w.data||[]).filter(x=>x.status==="pending").reduce((n,x)=>n+Number(x.amount_usd),0),withdrawals_paid:(w.data||[]).filter(x=>x.status==="paid").reduce((n,x)=>n+Number(x.amount_usd),0),hillscoin:(u.data||[]).reduce((n,x)=>n+Number(x.hillscoin),0),community:cp.data?.length||0,submission_status:["under_review","approved","rejected"].map(s=>({status:s,value:(sub.data||[]).filter(x=>x.status===s).length})),growth:[7,6,5,4,3,2,1].map((_,i)=>({label:`D${i+1}`,value:Math.max(0,(u.data||[]).length-i)}))})}catch(e){fail(res,e)}});

app.get("/api/admin/users",async(req,res)=>{try{await adminOnly(req);const{data}=await sb.from("users").select("*").order("created_at",{ascending:false});res.json({users:data||[]})}catch(e){fail(res,e)}});

app.post("/api/admin/users/:id/status",async(req,res)=>{try{await adminOnly(req);const s=req.body.status;if(!["active","suspended","deactivated","banned"].includes(s))throw Error("Invalid status.");const{data:x}=await sb.from("users").select("*").eq("id",req.params.id).single();let patch={status:s};if(s==="suspended"){patch.suspension_count=Number(x.suspension_count||0)+1;if(patch.suspension_count>=5)patch.status="deactivated"}await sb.from("users").update(patch).eq("id",req.params.id);res.json({ok:true})}catch(e){fail(res,e)}});

app.get("/api/admin/submissions",async(req,res)=>{try{await adminOnly(req);const{data}=await sb.from("submissions").select("*,user:users(telegram_id,telegram_username,first_name),task:tasks(title,reward)").eq("status","under_review").order("created_at");res.json({submissions:data||[]})}catch(e){fail(res,e)}});

app.post("/api/admin/submissions/:id/review",async(req,res)=>{try{const admin=await adminOnly(req);const{status,reject_reason}=req.body;if(!["approved","rejected"].includes(status))throw Error("Invalid review.");const{data:s}=await sb.from("submissions").select("*,task:tasks(*)").eq("id",req.params.id).single();if(!s||s.status!=="under_review")throw Error("Submission already reviewed.");const st=await settings();if(status==="rejected"){await sb.from("submissions").update({status,reject_reason:reject_reason||"",reviewer_id:admin.id,reviewed_at:new Date().toISOString()}).eq("id",s.id);await sb.from("users").update({xp:Math.max(0,(await sb.from("users").select("xp").eq("id",s.user_id).single()).data.xp-Number(st.rejection_xp_penalty)),trust_score:Math.max(0,Number((await sb.from("users").select("trust_score").eq("id",s.user_id).single()).data.trust_score)-Number(st.rejection_trust_penalty))}).eq("id",s.user_id);return res.json({ok:true})}const{data:u}=await sb.from("users").select("*").eq("id",s.user_id).single();const bonus=Number(u.current_streak)>=7?Number(s.task.reward)*Number(st.seven_day_task_bonus_percent)/100:0;const xp=Number(st.default_task_xp);await sb.from("submissions").update({status,reviewer_id:admin.id,reviewed_at:new Date().toISOString()}).eq("id",s.id);await sb.from("task_completions").insert({submission_id:s.id,task_id:s.task_id,user_id:s.user_id,reward:Number(s.task.reward)+bonus,xp,hillscoin:Number(st.default_hillscoin)});await sb.from("users").update({balance:Number(u.balance)+Number(s.task.reward)+bonus,xp:Number(u.xp)+xp,level:Math.floor((Number(u.xp)+xp)/100),hillscoin:Number(u.hillscoin)+Number(st.default_hillscoin)}).eq("id",u.id);await sb.from("activity_events").insert({user_id:u.id,type:"task_approved",amount:Number(s.task.reward)+bonus,xp_delta:xp});res.json({ok:true})}catch(e){fail(res,e)}});

app.post("/api/admin/tasks",async(req,res)=>{try{const x=await adminOnly(req);const{data,error}=await sb.from("tasks").insert({...req.body,created_by:x.id,reward:Number(req.body.reward||0),max_slots:Number(req.body.max_slots||1000)}).select("*").single();if(error)throw error;res.json({task:data})}catch(e){fail(res,e)}});
app.patch("/api/admin/tasks/:id",async(req,res)=>{try{await adminOnly(req);const{error}=await sb.from("tasks").update(req.body).eq("id",req.params.id);if(error)throw error;res.json({ok:true})}catch(e){fail(res,e)}});
app.delete("/api/admin/tasks/:id",async(req,res)=>{try{await adminOnly(req);const{error}=await sb.from("tasks").delete().eq("id",req.params.id);if(error)throw error;res.json({ok:true})}catch(e){fail(res,e)}});

app.post("/api/admin/events",async(req,res)=>{try{const x=await adminOnly(req);const{data,error}=await sb.from("events").insert({...req.body,created_by:x.id}).select("*").single();if(error)throw error;res.json({event:data})}catch(e){fail(res,e)}});

app.get("/api/admin/settings",async(req,res)=>{try{await adminOnly(req);res.json({settings:await settings()})}catch(e){fail(res,e)}});
app.post("/api/admin/settings",async(req,res)=>{try{await adminOnly(req);const allowed=["usd_ngn_rate","bank_withdrawal_fee_percent","bank_min_withdrawal","crypto_min_withdrawal","default_task_xp","default_hillscoin","rejection_xp_penalty","rejection_trust_penalty","reviewer_threshold_xp","reviewer_commission_percent","seven_day_task_bonus_percent","referral_money_amount","referral_percent","referral_money_enabled","referral_percent_enabled","ai_instructions"];const patch={};for(const k of allowed)if(k in req.body)patch[k]=req.body[k];const{error}=await sb.from("settings").update(patch).eq("id",true);if(error)throw error;res.json({ok:true})}catch(e){fail(res,e)}});

app.post("/api/assistant",async(req,res)=>{try{const st=await settings(),q=String(req.body.message||"").toLowerCase();let answer="I can help with tasks, proof submission, withdrawals, XP, trust score, referrals, ads and events. Tell me what part you need help with.";if(q.includes("proof"))answer="Open Earn, choose the task, complete the instructions, upload 1–3 screenshots and submit. Admin reviewers decide whether the proof is approved or rejected.";else if(q.includes("withdraw"))answer=`Withdrawals can use USDT BEP20, TRC20, TON or Nigerian bank accounts. Bank withdrawals use the admin-set ${st.bank_withdrawal_fee_percent}% fee and the admin-set USD/NGN rate. Processing is normally 5 minutes to 2–7 business days.`;else if(q.includes("xp"))answer=`Approved tasks give ${st.default_task_xp} XP by default. At ${st.reviewer_threshold_xp} XP, a user can apply for reviewer access when the admin enables it.`;else if(q.includes("trust"))answer="Rejected tasks reduce XP and trust according to the admin settings. Below the event threshold, event participation is restricted; at or below the ad-only threshold, ad activity is the remaining earning activity.";if(st.ai_instructions)answer+=" "+st.ai_instructions;res.json({answer})}catch(e){fail(res,e)}});

app.use(express.static(path.join(__dirname,"dist")));
app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,"dist","index.html")));
app.listen(process.env.PORT||3000);

export default app;
