import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import{Menu,X,Bell,Sparkles,PlayCircle,Wallet,Users,User,CalendarDays,Trophy,ShieldCheck,Bot,Activity,Download,Send,Clock3,CheckCircle2,XCircle,Search,Plus,Trash2,Edit3,Eye,Lock,Gift,Landmark,Coins,MessageCircle,Image as ImageIcon,Video,AlertTriangle,ChevronRight,Settings,LogOut,ArrowUpRight}from"lucide-react";
import"./styles.css";

const tg=window.Telegram?.WebApp;
const user=()=>tg?.initDataUnsafe?.user||null;
async function api(path,opt={}){
 const headers={"X-Telegram-Init-Data":tg?.initData||"",...(opt.headers||{})};
 if(opt.body && !(opt.body instanceof FormData))headers["Content-Type"]="application/json";
 const r=await fetch(path,{...opt,headers});
 const d=await r.json().catch(()=>({}));
 if(!r.ok)throw Error(d.error||"Request failed");
 return d;
}
const money=v=>"$"+Number(v||0).toFixed(2);
const initials=u=>(u?.first_name||"H").slice(0,1).toUpperCase();

function App(){
 const[u,setU]=useState(null),[tab,setTab]=useState("dashboard"),[drawer,setDrawer]=useState(false),[admin,setAdmin]=useState(false),[toast,setToast]=useState(""),[refresh,setRefresh]=useState(0);
 const[loading,setLoading]=useState(true);
 const load=async()=>{try{setLoading(true);const d=await api("/api/bootstrap");setU(d.user);setAdmin(d.admin)}catch(e){setToast(e.message)}finally{setLoading(false)}};
 useEffect(()=>{tg?.ready();tg?.expand();load()},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(t)}},[toast]);
 if(!tg?.initData)return <div className="outside"><div className="logo">H</div><h1>HillsByte</h1><p>Open this page from the HillsByte Telegram Mini App.</p></div>;
 if(loading&&!u)return <div className="outside"><div className="logo pulse">H</div><p>Loading HillsByte…</p></div>;
 const go=id=>{setTab(id);setDrawer(false);setRefresh(x=>x+1)};
 const nav=[
  ["dashboard","Dashboard",Sparkles],["earn","Earn",Sparkles],["ads","Ads",PlayCircle],["assistant","Assistant",Bot],
  ["activity","Activity",Activity],["wallet","Wallet",Wallet],["referrals","Referrals",Users],["community","Community",Users],
  ["events","Events",CalendarDays],["leaderboard","Leaderboard",Trophy],["notifications","Notifications",Bell],["profile","Profile",User]
 ];
 return <div className="app">
  <header className="header"><button className="iconBtn" onClick={()=>setDrawer(true)}><Menu/></button><div className="brandLine"><span className="avatar mini">{initials(u)}</span><b>HillsByte</b></div><button className="iconBtn notify" onClick={()=>go("notifications")}><Bell/><i>1</i></button></header>
  {drawer&&<><div className="shade" onClick={()=>setDrawer(false)}/><aside className="drawer"><div className="drawerHead"><span className="avatar">H</span><b>HillsByte</b><button className="iconBtn" onClick={()=>setDrawer(false)}><X/></button></div>{nav.map(([id,l,I])=><button className={"drawerItem "+(tab===id?"selected":"")} key={id} onClick={()=>go(id)}><I/><span>{l}</span></button>)}{admin&&<button className={"drawerItem "+(tab==="admin"?"selected":"")} onClick={()=>go("admin")}><ShieldCheck/><span>Admin</span></button>}</aside></>}
  <main>
   {u?.status!=="active"&&<div className="warning"><AlertTriangle/><div><b>Account {u.status}</b><span>Your account currently has restricted access.</span></div></div>}
   {tab==="dashboard"&&<Dashboard u={u} go={go} refresh={refresh}/>}
   {tab==="earn"&&<Earn go={go} refresh={refresh}/>}
   {tab==="ads"&&<Ads refresh={refresh} toast={setToast}/>}
   {tab==="assistant"&&<Assistant toast={setToast}/>}
   {tab==="activity"&&<ActivityPage u={u} refresh={refresh}/>}
   {tab==="wallet"&&<WalletPage u={u} toast={setToast} refresh={refresh}/>}
   {tab==="referrals"&&<Referrals u={u} refresh={refresh}/>}
   {tab==="community"&&<Community u={u} toast={setToast} refresh={refresh}/>}
   {tab==="events"&&<Events u={u} refresh={refresh}/>}
   {tab==="leaderboard"&&<Leaderboard refresh={refresh}/>}
   {tab==="notifications"&&<Notifications refresh={refresh}/>}
   {tab==="profile"&&<Profile u={u} toast={setToast} refresh={refresh}/>}
   {tab==="admin"&&admin&&<Admin toast={setToast} refresh={refresh}/>}
  </main>
  <nav className="bottom">{[["earn","Earn",Sparkles],["ads","Ads",PlayCircle],["wallet","Wallet",Wallet],["community","Community",Users],["profile","Profile",User]].map(([id,l,I])=><button key={id} className={tab===id?"active":""} onClick={()=>go(id)}><I/><span>{l}</span></button>)}</nav>
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Dashboard({u,go,refresh}){
 const[d,setD]=useState(null);
 useEffect(()=>{api("/api/dashboard").then(setD).catch(()=>{})},[refresh]);
 const quick=[["Community",Users,"community","red"],["Events",CalendarDays,"events","teal"],["Leaderboard",Trophy,"leaderboard","purple"],["Profile",User,"profile","dark"],["Earn",Sparkles,"earn","green"],["Wallet",Wallet,"wallet","blue"],["Referral",Users,"referrals","purple"],["Activity",Activity,"activity","gold"]];
 return <section className="page">
  <div className="hero"><div><small>AVAILABLE BALANCE</small><strong>{money(u.balance)}</strong><span>Pending {money(u.pending_balance)}</span></div><div className="coin">H</div></div>
  <div className="metricGrid"><Metric label="Trust score" value={Number(u.trust_score||100).toFixed(1)} icon={ShieldCheck}/><Metric label="XP / Level" value={`${u.xp} / ${u.level}`} icon={Trophy}/><Metric label="HillsCoin" value={u.hillscoin} icon={Coins}/></div>
  <div className="checkin"><div className="checkTop"><div className="flame">♨</div><div><b>Daily check-in</b><span>Current streak: {u.current_streak} days</span></div><button onClick={()=>api("/api/checkin",{method:"POST"}).then(()=>location.reload()).catch(()=>{})}>{u.checked_today?"Checked in":"Check in"}</button></div><div className="days">{["D1","D2","D3","D4","D5","D6","D7"].map((x,i)=><span className={(i<u.current_streak?"on":"")} key={x}>{x}</span>)}</div></div>
  <h2>Quick actions</h2><div className="quickGrid">{quick.map(([l,I,id,c])=><button key={id} onClick={()=>go(id)}><span className={"quickIcon "+c}><I/></span><label>{l}</label></button>)}</div>
  <div className="sectionHead"><h2>Recent activity</h2><button onClick={()=>go("activity")}>View all →</button></div>
  <div className="empty big"><div className="emptyIcon"><Activity/></div><b>{d?.recent?.length?"Latest activity":"No earnings yet"}</b><span>{d?.recent?.length?"Your latest HillsByte activity is ready.":"Complete your first task to start earning."}</span><button onClick={()=>go("earn")}>Find tasks</button></div>
 </section>
}
function Metric({label,value,icon:I}){return <div className="metric"><I/><b>{value}</b><span>{label}</span></div>}

function Earn({go,refresh}){
 const[tasks,setTasks]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[attempt,setAttempt]=useState(null),[files,setFiles]=useState([]),[note,setNote]=useState("");
 const load=()=>api("/api/tasks").then(x=>setTasks(x.tasks||[])).catch(()=>{});
 useEffect(load,[refresh]);
 const list=useMemo(()=>tasks.filter(t=>!q||t.title.toLowerCase().includes(q.toLowerCase())),[tasks,q]);
 const start=async t=>{try{const d=await api(`/api/tasks/${t.id}/start`,{method:"POST"});if(d.blockedByTrust)throw Error(d.message);if(d.sponsorRequired){await api("/api/ads/complete",{method:"POST"});}setSelected(t);setAttempt(d.attempt)}catch(e){alert(e.message)}};
 const submit=async()=>{if(!files.length)return alert("Upload at least one screenshot.");try{const paths=[];for(const f of files){const s=await api("/api/upload-url",{method:"POST",body:JSON.stringify({bucket:"hillsbyte-proofs",ext:f.name.split(".").pop(),type:f.type})});const up=await fetch(`${s.url}`,{method:"POST",headers:{"Content-Type":f.type,"x-upsert":"false","x-signature":s.token},body:f});if(!up.ok)throw Error("Proof upload failed.");paths.push(s.path)}await api("/api/submissions",{method:"POST",body:JSON.stringify({attemptId:attempt.id,taskId:selected.id,proofPaths:paths,note})});setSelected(null);setAttempt(null);setFiles([]);load();alert("Proof submitted for review.")}catch(e){alert(e.message)}};
 if(selected)return <section className="page"><button className="back" onClick={()=>setSelected(null)}>← Back to tasks</button><div className="runner"><div className="runnerTop"><span className="taskLogo">✓</span><div><b>{selected.title}</b><span>{money(selected.reward)} reward</span></div><strong>{Math.max(0,Math.floor((new Date(attempt.expires_at)-Date.now())/1000))}s</strong></div>{selected.image_url&&<img className="taskImage" src={selected.image_url}/>}<h3>How to complete</h3><p className="copy">{selected.description}</p>{selected.task_url&&<a className="link" href={selected.task_url} target="_blank">Open task link ↗</a>}<label className="upload"><ImageIcon/><b>Add proof screenshots</b><span>1–3 images</span><input type="file" accept="image/*" multiple onChange={e=>setFiles([...e.target.files].slice(0,3))}/></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note for the reviewer (optional)"/><button className="primary" onClick={submit}>Submit for review</button></div></section>;
 return <section className="page"><div className="sectionHead"><div><h2>Earn</h2><p>Complete tasks and submit proof.</p></div><span className="pill">{tasks.length} tasks</span></div><div className="search"><Search/><input placeholder="Search tasks..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="taskList">{list.map(t=><Task key={t.id} t={t} start={()=>start(t)}/>)}</div>{!list.length&&<div className="empty">No active tasks right now.</div>}</section>
}
function Task({t,start}){const pct=Math.min(100,Math.round(t.completed/t.max_slots*100));return <article className="task"><div className="taskRow"><span className="taskLogo">✦</span><div className="taskInfo"><b>{t.title}</b><p>{t.short_description||t.description}</p></div><strong>{money(t.reward)}</strong></div><div className="taskMeta"><span><Clock3/> {t.timer_seconds}s</span><span>{Math.max(0,t.daily_slots-t.today)} today</span><span>{Math.max(0,t.max_slots-t.completed)} left</span></div><div className="progress"><i style={{width:pct+"%"}}/></div><button className="taskBtn" onClick={start}>View task <ArrowUpRight/></button></article>}

function Ads({toast,refresh}){
 const[d,setD]=useState({views:0});useEffect(()=>{api("/api/ads").then(setD).catch(()=>{})},[refresh]);
 const watch=async()=>{try{toast("Opening sponsor ad…");if(typeof window.show_11725898==="function")await window.show_11725898();await api("/api/ads/complete",{method:"POST"});toast("Valid ad view recorded.");setD(await api("/api/ads"))}catch(e){toast(e.message)}};
 return <section className="page"><div className="adsHero"><div className="bigIcon"><PlayCircle/></div><div><h2>Watch an ad</h2><p>Each completed ad counts as a valid ad view. Valid ad views can unlock referral progress.</p></div></div><button className="primary adButton" onClick={watch}><PlayCircle/> Watch ad</button><div className="adCard"><div><b>✦ Valid ad views</b><strong>{d.views||0}</strong></div><span>Referral unlock progress</span><div className="adProgress"><i style={{width:Math.min(100,(d.views||0)/5*100)+"%"}}/></div><p>Once you complete 5 valid ad views, referral progress can be released according to the admin settings.</p></div></section>
}

function Assistant(){
 const[msg,setMsg]=useState(""),[items,setItems]=useState([{r:0,t:"Hi! I’m the HillsByte assistant. I can explain tasks, proof submission, withdrawals, XP, trust score, referrals and events."}]);
 const send=async()=>{if(!msg.trim())return;const x=msg;setMsg("");setItems(a=>[...a,{r:1,t:x}]);try{const d=await api("/api/assistant",{method:"POST",body:JSON.stringify({message:x})});setItems(a=>[...a,{r:0,t:d.answer}])}catch(e){setItems(a=>[...a,{r:0,t:e.message}])}};
 return <section className="page"><div className="assistantHero"><div className="bigIcon"><Bot/></div><div><h2>HillsByte Assistant</h2><p>Dedicated help for using the app.</p></div></div><div className="chat">{items.map((m,i)=><div className={"bubble "+(m.r?"me":"")} key={i}>{m.t}</div>)}</div><div className="chatInput"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask HillsByte…"/><button onClick={send}><Send/></button></div></section>
}

function ActivityPage({u,refresh}){
 const[d,setD]=useState({chart:[],history:[]});useEffect(()=>{api("/api/activity").then(setD).catch(()=>{})},[refresh]);const max=Math.max(1,...(d.chart||[]).map(x=>x.value));
 return <section className="page"><h2>Activity</h2><div className="chartCard"><h3>Earnings over time</h3><div className="lineChart">{(d.chart||[]).map((x,i)=><div className="chartCol" key={i}><i style={{height:(x.value/max*100)+"%"}}/><small>{x.label}</small></div>)}</div></div><div className="historyCard"><h3>Task history</h3>{(d.history||[]).map(x=><div className="historyRow" key={x.id}><span className={x.status}><CheckCircle2/></span><div><b>{x.title}</b><small>{x.status}</small></div><strong>{money(x.reward)}</strong></div>)}{!d.history?.length&&<div className="empty">No activity yet.</div>}</div></section>
}

function WalletPage({u,toast,refresh}){
 const[s,setS]=useState({settings:{}}),[method,setMethod]=useState("bank"),[f,setF]=useState({});useEffect(()=>{api("/api/wallet").then(setS).catch(()=>{})},[refresh]);
 const req=async()=>{try{await api("/api/withdrawals",{method:"POST",body:JSON.stringify({method,...f})});toast("Withdrawal request submitted.");}catch(e){toast(e.message)}};
 return <section className="page"><div className="walletHero"><small>Available to withdraw</small><b>{money(u.balance)}</b><span>Pending {money(u.pending_balance)}</span></div><div className="methodGrid"><button className={method==="bank"?"selected":""} onClick={()=>setMethod("bank")}><Landmark/>Bank</button><button className={method==="crypto"?"selected":""} onClick={()=>setMethod("crypto")}><Wallet/>Crypto</button></div>{method==="bank"?<div className="formGrid"><input placeholder="Account holder name" onChange={e=>setF({...f,account_name:e.target.value})}/><input placeholder="Account number" onChange={e=>setF({...f,account_number:e.target.value})}/><select onChange={e=>setF({...f,bank_name:e.target.value})}><option value="">Select Nigerian bank / wallet</option>{["Opay","PalmPay","Moniepoint","GTBank","Access Bank","First Bank","UBA","Zenith Bank","Kuda","Stanbic IBTC","Fidelity Bank","FCMB","Union Bank","Sterling Bank","Wema Bank","Polaris Bank","Ecobank","Keystone Bank","Jaiz Bank","Heritage Bank"].map(x=><option key={x}>{x}</option>)}</select><div className="rateBox">Rate: 1 USD = ₦{Number(s.settings?.usd_ngn_rate||1500).toLocaleString()} · Fee: {s.settings?.bank_withdrawal_fee_percent||10}%<br/><b>You receive approximately ₦{(Number(u.balance||0)*(1-Number(s.settings?.bank_withdrawal_fee_percent||10)/100)*Number(s.settings?.usd_ngn_rate||1500)).toLocaleString(undefined,{maximumFractionDigits:2})}</b></div></div>:<div className="formGrid"><select onChange={e=>setF({...f,network:e.target.value})}><option>BEP20</option><option>TRC20</option><option>TON</option></select><input placeholder="Wallet address" onChange={e=>setF({...f,address:e.target.value})}/></div>}<button className="primary" onClick={req}>Request withdrawal</button><p className="muted">Normal processing: 5 minutes to 2–7 business days.</p></section>
}

function Referrals({u,refresh}){
 const[d,setD]=useState({});useEffect(()=>{api("/api/referrals").then(setD).catch(()=>{})},[refresh]);return <section className="page"><div className="refHero"><Users/><small>REFERRAL PROGRAM</small><h2>Invite friends. Earn more.</h2><p>Your referral rate is controlled by the admin.</p><div className="refCode">{d.code||"—"}</div><button className="primary" onClick={()=>navigator.clipboard?.writeText(d.link||"")}>Copy invite link</button></div><div className="panel"><h3>Team growth</h3><div className="teamStats"><div><b>{d.total||0}</b><span>Total referrals</span></div><div><b>{d.pending||0}</b><span>Pending</span></div><div><b>{money(d.commissions)}</b><span>Commission</span></div></div><p className="muted">Requirements are configurable: channel join, 4 tasks, 50 XP, and first withdrawal. Admin can choose any combination.</p></div></section>
}

function Community({u,toast,refresh}){
 const[posts,setPosts]=useState([]),[text,setText]=useState(""),[comment,setComment]=useState({});const load=()=>api("/api/community").then(x=>setPosts(x.posts||[])).catch(()=>{});useEffect(load,[refresh]);
 const post=async()=>{try{await api("/api/community",{method:"POST",body:JSON.stringify({body:text})});setText("");load()}catch(e){toast(e.message)}};
 return <section className="page"><div className="sectionHead"><div><h2>Community</h2><p>Ask questions and share your opinion.</p></div><Users/></div><div className="communityComposer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What do you want to ask?"/><button className="primary" onClick={post}>Post</button><small>Pictures/videos are unlocked after your first withdrawal.</small></div>{posts.map(p=><article className="post" key={p.id}><div className="postHead"><span className="avatar">{initials(p.user)}</span><div><b>@{p.user?.telegram_username||"member"}</b><small>{new Date(p.created_at).toLocaleString()}</small></div></div><p>{p.body}</p><div className="comments">{(p.comments||[]).map(c=><div key={c.id}><b>@{c.user?.telegram_username||"member"}</b> {c.body}</div>)}</div><div className="commentInput"><input placeholder="Comment…" value={comment[p.id]||""} onChange={e=>setComment({...comment,[p.id]:e.target.value})}/><button onClick={async()=>{await api(`/api/community/${p.id}/comments`,{method:"POST",body:JSON.stringify({body:comment[p.id]})});load()}}><Send/></button></div></article>)}</section>
}

function Events({refresh}){
 const[d,setD]=useState([]);useEffect(()=>{api("/api/events").then(x=>setD(x.events||[])).catch(()=>{})},[refresh]);return <section className="page"><h2>Events</h2>{d.map(e=><article className="event" key={e.id}>{(e.banner_url||e.use_default_3d)&&<div className="event3d">{e.banner_url?<img src={e.banner_url}/>:<div className="coin3d">H</div>}</div>}<h3>{e.title}</h3><p>{e.description}</p><div className="eventMeta"><span>{new Date(e.starts_at).toLocaleString()}</span><span>{e.reward}</span></div></article>)}{!d.length&&<div className="empty">No events yet.</div>}</section>
}
function Leaderboard({refresh}){const[d,setD]=useState([]);useEffect(()=>{api("/api/leaderboard").then(x=>setD(x.users||[])).catch(()=>{})},[refresh]);return <section className="page"><h2>Leaderboard</h2>{d.map((x,i)=><div className="leader" key={x.telegram_id}><span>#{i+1}</span><span className="avatar">{initials(x)}</span><div><b>{x.display_username||x.first_name}</b><small>{x.xp} XP</small></div><strong>{x.completed} tasks</strong></div>)}</section>}
function Notifications({refresh}){const[d,setD]=useState([]);useEffect(()=>{api("/api/notifications").then(x=>setD(x.notifications||[])).catch(()=>{})},[refresh]);return <section className="page"><h2>Notifications</h2>{d.map(x=><div className="notification" key={x.id}><Bell/><div><b>{x.title}</b><p>{x.message}</p><small>{new Date(x.created_at).toLocaleString()}</small></div></div>)}</section>}

function Profile({u,toast,refresh}){
 const[edit,setEdit]=useState(u.display_username||""),[d,setD]=useState(null);useEffect(()=>{api("/api/profile").then(setD).catch(()=>{})},[refresh]);
 const save=async()=>{try{await api("/api/profile",{method:"POST",body:JSON.stringify({display_username:edit})});toast("Profile updated.")}catch(e){toast(e.message)}};
 return <section className="page"><div className="profileHero"><span className="avatar large">{initials(u)}</span><div><small>HILLSBYTE MEMBER</small><h2>{u.first_name||"Member"}</h2><p>@{u.telegram_username||"telegram_user"} · Telegram ID {u.telegram_id}</p></div><span className="status">{u.status}</span></div><div className="profileStats"><Metric label="Tasks completed" value={d?.completed||0} icon={CheckCircle2}/><Metric label="Streak" value={u.current_streak} icon={Sparkles}/><Metric label="Trust" value={Number(u.trust_score).toFixed(1)} icon={ShieldCheck}/></div><div className="panel"><h3>Edit profile</h3><input value={edit} onChange={e=>setEdit(e.target.value)} placeholder="In-app username"/><button className="primary" onClick={save}>Save username</button><p className="muted">Your Telegram username and Telegram ID remain visible to admins for identification.</p></div><div className="panel"><h3>Redeem code</h3><Redeem toast={toast}/></div><div className="panel"><h3>Streak history & event participation</h3><div className="miniCalendar">{(d?.streak||[]).map(x=><span className={x?"on":""} key={x}>{x}</span>)}</div><p className="muted">{d?.events?.length||0} event(s) currently participating.</p></div></section>
}
function Redeem({toast}){const[c,setC]=useState("");return <div className="inline"><input value={c} onChange={e=>setC(e.target.value)} placeholder="Enter redeem code"/><button onClick={()=>api("/api/redeem",{method:"POST",body:JSON.stringify({code:c})}).then(()=>toast("Redeemed successfully.")).catch(e=>toast(e.message))}>Redeem</button></div>}

function Admin({toast,refresh}){
 const[tab,setTab]=useState("overview"),[d,setD]=useState(null),[users,setUsers]=useState([]),[subs,setSubs]=useState([]),[tasks,setTasks]=useState([]),[events,setEvents]=useState([]),[settings,setSettings]=useState(null),[selected,setSelected]=useState(null);
 const load=async()=>{try{setD(await api("/api/admin/overview"));setUsers((await api("/api/admin/users")).users||[]);setSubs((await api("/api/admin/submissions")).submissions||[]);setTasks((await api("/api/tasks")).tasks||[]);setEvents((await api("/api/events")).events||[]);setSettings((await api("/api/admin/settings")).settings)}catch(e){toast(e.message)}};useEffect(load,[refresh]);
 const review=async(id,status)=>{let reason="";if(status==="rejected")reason=prompt("Reject reason (optional):")||"";try{await api(`/api/admin/submissions/${id}/review`,{method:"POST",body:JSON.stringify({status,reject_reason:reason})});load()}catch(e){toast(e.message)}};
 const status=async(id,s)=>{try{await api(`/api/admin/users/${id}/status`,{method:"POST",body:JSON.stringify({status:s})});load()}catch(e){toast(e.message)}};
 return <section className="page admin"><div className="adminTitle"><div><small>ADMIN CONTROL CENTER</small><h2>HillsByte</h2></div><button onClick={load}><Activity/></button></div><div className="adminTabs">{["overview","tasks","proofs","users","events","settings"].map(x=><button className={tab===x?"selected":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==="overview"&&<><div className="adminStats">{[["Revenue",d?.revenue],["Pending revenue",d?.pending_revenue],["Task completed",d?.tasks_completed],["Ads watched",d?.ads_watched],["Users",d?.users],["Pending referrals",d?.pending_referrals],["Pending withdrawals",d?.pending_withdrawals],["Withdrawals paid",d?.withdrawals_paid],["HillsCoin",d?.hillscoin],["Community activity",d?.community]].map(([l,v])=><Metric key={l} label={l} value={typeof v==="number"&&l.toLowerCase().includes("revenue")?money(v):v??0} icon={Activity}/>)}</div><div className="chartCard"><h3>Task submissions by status</h3><Bars data={d?.submission_status||[]}/></div><div className="chartCard"><h3>User growth</h3><Bars data={d?.growth||[]}/></div></>}
 {tab==="tasks"&&<TaskAdmin tasks={tasks} reload={load} toast={toast}/>}
 {tab==="proofs"&&<div className="adminList">{subs.map(s=><div className="submission"><div><b>{s.user?.telegram_username||s.user?.telegram_id}</b><small>{s.task?.title} · {new Date(s.created_at).toLocaleString()}</small></div><div className="proofBtns"><button onClick={()=>setSelected(s)}><Eye/></button><button className="ok" onClick={()=>review(s.id,"approved")}><CheckCircle2/></button><button className="bad" onClick={()=>review(s.id,"rejected")}><XCircle/></button></div></div>)}{selected&&<ProofModal s={selected} close={()=>setSelected(null)} review={review}/>}</div>}
 {tab==="users"&&<div className="adminList">{users.map(x=><div className="userAdmin" key={x.id} onClick={()=>setSelected(x)}><span className="avatar">{initials(x)}</span><div><b>@{x.telegram_username||"no_username"}</b><small>ID {x.telegram_id} · {x.display_username||"no app username"} · XP {x.xp} · Trust {x.trust_score}</small></div><div className="userBtns"><button onClick={e=>{e.stopPropagation();status(x.id,x.status==="active"?"suspended":"active")}}>{x.status==="active"?"Suspend":"Activate"}</button><button onClick={e=>{e.stopPropagation();status(x.id,"banned")}}>Ban</button></div></div>)}</div>}
 {tab==="events"&&<EventAdmin events={events} reload={load} toast={toast}/>}
 {tab==="settings"&&<SettingsAdmin s={settings} reload={load} toast={toast}/>}
 </section>
}
function Bars({data=[]}){const max=Math.max(1,...data.map(x=>Number(x.value||x.count||0)));return <div className="bars">{data.map((x,i)=><div className="bar" key={i}><span>{x.label||x.status}</span><i style={{height:(Number(x.value||x.count||0)/max*100)+"%"}}/><b>{x.value||x.count||0}</b></div>)}</div>}
function ProofModal({s,close,review}){return <div className="modal"><div className="modalBox"><div className="modalHead"><div><h3>Proof review</h3><small>{s.user?.telegram_username||s.user?.telegram_id} · {s.task?.title}</small></div><button onClick={close}><X/></button></div><div className="proofGrid">{(s.proof_paths||[]).map((p,i)=><img key={i} src={p} onError={e=>e.currentTarget.style.display="none"}/>)}</div><p className="copy">{s.note||"No note supplied."}</p><div className="modalActions"><button className="ok" onClick={()=>{review(s.id,"approved");close()}}>Approve</button><button className="bad" onClick={()=>{review(s.id,"rejected");close()}}>Reject / reason</button></div></div></div>}
function TaskAdmin({tasks,reload,toast}){const[f,setF]=useState({});const save=async()=>{try{await api("/api/admin/tasks",{method:"POST",body:JSON.stringify(f)});setF({});reload()}catch(e){toast(e.message)}};return <div><div className="panel"><h3>New task</h3><div className="formGrid"><input placeholder="Title" onChange={e=>setF({...f,title:e.target.value})}/><input placeholder="Reward USD" type="number" onChange={e=>setF({...f,reward:e.target.value})}/><textarea className="wide" placeholder="Description" onChange={e=>setF({...f,description:e.target.value})}/><input placeholder="Task URL" onChange={e=>setF({...f,task_url:e.target.value})}/><input placeholder="Max slots" type="number" onChange={e=>setF({...f,max_slots:e.target.value})}/><label className="check"><input type="checkbox" checked={f.sponsor_ad_required!==false} onChange={e=>setF({...f,sponsor_ad_required:e.target.checked})}/> Start each task with a sponsored ad</label></div><button className="primary" onClick={save}>Post task</button></div><div className="adminList">{tasks.map(t=><div className="submission" key={t.id}><div><b>{t.title}</b><small>{money(t.reward)} · {t.active?"active":"inactive"}</small></div><div className="proofBtns"><button onClick={()=>api(`/api/admin/tasks/${t.id}`,{method:"PATCH",body:JSON.stringify({active:!t.active})}).then(reload)}>{t.active?"Deactivate":"Activate"}</button><button className="bad" onClick={()=>api(`/api/admin/tasks/${t.id}`,{method:"DELETE"}).then(reload)}><Trash2/></button></div></div>)}</div></div>}
function EventAdmin({events,reload,toast}){const[f,setF]=useState({use_default_3d:true});const save=async()=>{try{await api("/api/admin/events",{method:"POST",body:JSON.stringify(f)});setF({use_default_3d:true});reload()}catch(e){toast(e.message)}};return <div><div className="panel"><h3>Add event</h3><div className="formGrid"><input placeholder="Title" onChange={e=>setF({...f,title:e.target.value})}/><textarea className="wide" placeholder="Description" onChange={e=>setF({...f,description:e.target.value})}/><input placeholder="Banner URL (optional)" onChange={e=>setF({...f,banner_url:e.target.value})}/><label className="check"><input type="checkbox" checked={f.use_default_3d} onChange={e=>setF({...f,use_default_3d:e.target.checked})}/> Use animated 3D HillsByte banner</label><input type="datetime-local" onChange={e=>setF({...f,starts_at:e.target.value})}/><input placeholder="Reward" onChange={e=>setF({...f,reward:e.target.value})}/><textarea className="wide" placeholder="Rules" onChange={e=>setF({...f,rules:e.target.value})}/><input placeholder="CTA label" onChange={e=>setF({...f,cta_label:e.target.value})}/><input placeholder="CTA URL" onChange={e=>setF({...f,cta_url:e.target.value})}/></div><button className="primary" onClick={save}>Create event</button></div>{events.map(e=><div className="submission" key={e.id}><div><b>{e.title}</b><small>{new Date(e.starts_at).toLocaleString()}</small></div></div>)}</div>}
function SettingsAdmin({s,reload,toast}){const[v,setV]=useState(s||{});useEffect(()=>setV(s||{}),[s]);const save=async()=>{try{await api("/api/admin/settings",{method:"POST",body:JSON.stringify(v)});toast("Settings saved.");reload()}catch(e){toast(e.message)}};if(!s)return <div className="empty">Loading settings…</div>;return <div className="panel"><h3>Admin wallet & rules</h3><div className="formGrid">{[["usd_ngn_rate","USD → NGN rate"],["bank_withdrawal_fee_percent","Bank withdrawal fee %"],["bank_min_withdrawal","Bank minimum USD"],["crypto_min_withdrawal","Crypto minimum USD"],["default_task_xp","XP per task"],["default_hillscoin","HillsCoin per task"],["rejection_xp_penalty","Rejected XP penalty"],["rejection_trust_penalty","Rejected trust penalty"],["reviewer_threshold_xp","Reviewer XP threshold"],["reviewer_commission_percent","Reviewer commission %"],["seven_day_task_bonus_percent","7-day streak task bonus %"],["referral_money_amount","Referral event amount"],["referral_percent","Referral percentage"]].map(([k,l])=><label key={k}><span>{l}</span><input type="number" value={v[k]??0} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}<label className="check"><input type="checkbox" checked={!!v.referral_money_enabled} onChange={e=>setV({...v,referral_money_enabled:e.target.checked})}/> Referral money ON</label><label className="check"><input type="checkbox" checked={!!v.referral_percent_enabled} onChange={e=>setV({...v,referral_percent_enabled:e.target.checked})}/> Referral percentage ON</label><textarea className="wide" value={v.ai_instructions||""} onChange={e=>setV({...v,ai_instructions:e.target.value})} placeholder="AI assistant instructions / task help"/></div><button className="primary" onClick={save}>Save settings</button></div>}

createRoot(document.getElementById("root")).render(<App/>);
