'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUp, Bell, Bot, Calendar, Check, ChevronDown, Coin, Download, Edit, ImageIcon, Menu, Message, More, Play, Plus, Search, Shield, Spark, Trophy, Trash, User, Users, Wallet, Warning, X } from '@/lib/icons';
import { getTelegramWebApp } from '@/lib/telegram';

type Screen='dashboard'|'earn'|'ads'|'wallet'|'community'|'profile'|'leaderboard'|'activity'|'referrals'|'events'|'admin'|'assistant';
const nav:[Screen,string,React.ComponentType<any>][]=[['dashboard','Dashboard',Activity],['earn','Earn',Spark],['ads','Ads',Play],['assistant','Assistant',Bot],['activity','Activity',Activity],['wallet','Wallet',Wallet],['referrals','Referrals',Users],['community','Community',Users],['events','Events',Calendar],['leaderboard','Leaderboard',Trophy],['profile','Profile',User]];
const quick:[Screen,string,React.ComponentType<any>,string][]=[['earn','Earn',Spark,'green'],['wallet','Wallet',Wallet,'blue'],['referrals','Referral',Users,'purple'],['activity','Activity',ArrowUp,'gold'],['community','Community',Users,'red'],['events','Events',Calendar,'green'],['leaderboard','Leaderboard',Trophy,'purple'],['profile','Profile',User,'neutral']];

export default function Home(){
 const [screen,setScreen]=useState<Screen>('dashboard'); const [drawer,setDrawer]=useState(false); const [modal,setModal]=useState<string|null>(null); const [admin,setAdmin]=useState(false); const [tgName,setTgName]=useState('HillsByte');
 useEffect(()=>{const tg=getTelegramWebApp();tg?.ready();tg?.expand();const u=tg?.initDataUnsafe?.user;if(u){setTgName(u.first_name||u.username||'HillsByte');void fetch('/api/telegram/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData:tg?.initData||''})}).catch(()=>{});}},[]);
 const title=screen==='dashboard'?'':screen[0].toUpperCase()+screen.slice(1);
 return <div className="shell"><div className="phone">
   <TelegramBar />
   <header className="apphead"><button className="iconbtn" onClick={()=>setDrawer(true)} aria-label="Open menu"><Menu size={32}/></button><div className="brand"><div className="avatar">H</div>{tgName}</div><button className="iconbtn bell" onClick={()=>setScreen('activity')} aria-label="Notifications"><Bell size={31}/><span className="badge">1</span></button></header>
   {screen==='dashboard'&&<Dashboard onNav={setScreen} onModal={setModal}/>} 
   {screen==='earn'&&<Earn onNav={setScreen}/>} {screen==='ads'&&<Ads/>} {screen==='wallet'&&<WalletPage/>} {screen==='community'&&<Community/>} {screen==='profile'&&<Profile/>} {screen==='leaderboard'&&<Leaderboard/>} {screen==='activity'&&<ActivityPage/>} {screen==='referrals'&&<Referrals/>} {screen==='events'&&<Events/>} {screen==='assistant'&&<Assistant/>} {screen==='admin'&&<Admin/>}
   <Bottom active={screen} setScreen={setScreen}/>
   {drawer&&<Drawer active={screen} close={()=>setDrawer(false)} setScreen={setScreen} admin={admin} setAdmin={setAdmin}/>} 
   {modal&&<Modal kind={modal} close={()=>setModal(null)}/>} 
 </div></div>
}

function TelegramBar(){return <div className="tgbar"><div className="top"><span className="tgx">×</span><b>CPABYTE</b><span className="tgspacer"/><ChevronDown size={36}/><More size={30}/></div></div>}
function Dashboard({onNav,onModal}:{onNav:(s:Screen)=>void;onModal:(s:string)=>void}){return <main className="content">
 <section className="card check-card"><div className="check-title"><div className="fire">🔥</div><div><div className="title">Daily check-in</div><div className="sub">Current streak: 3<br/>days</div></div></div><button className="checked" onClick={()=>onModal('checkin')}><Check size={29}/>Checked<br/>in</button><div className="days">{['D1','D2','D3','D4','D5','D6','D7'].map((d,i)=><div className={'day '+(i<3?'done':'')} key={d}>{d}</div>)}</div></section>
 <div className="section-head"><h2>Quick actions</h2></div><div className="quick">{quick.map(([s,l,I,c])=><button key={s} onClick={()=>onNav(s)}><div className={'quick-icon '+c}><I size={44}/></div><span>{l}</span></button>)}</div>
 <div className="section-head"><h2>Recent activity</h2><button className="link" onClick={()=>onNav('activity')}>View all →</button></div><section className="card empty"><div className="empty-icon"><ArrowUp size={54}/></div><h2>No earnings yet</h2><p>Complete your first task to start earning.</p><button className="primary" onClick={()=>onNav('earn')}>Find tasks</button></section>
 </main>}

function Earn({onNav}:{onNav:(s:Screen)=>void}){return <main className="content"><div className="section-head"><h2>Available tasks</h2><span className="link">0 active</span></div><div className="notice"><Warning size={24}/> Every task starts with a sponsored ad. Complete it, submit proof and wait for review.</div><div style={{height:16}}/><div className="task-card"><h3>Write a short review</h3><div className="sub" style={{fontSize:16}}>Earn $0.50 • +10 XP • +2 HillsCoin</div><div className="task-meta" style={{marginTop:12}}><span className="tag">Sponsored ad</span><span className="tag">Proof required</span></div><button className="primary" style={{marginTop:18}} onClick={()=>onNav('ads')}>Start task</button></div><div className="task-card"><h3>Follow HillsByte on Telegram</h3><div className="sub" style={{fontSize:16}}>Earn $0.25 • +10 XP • +2 HillsCoin</div><div className="task-meta" style={{marginTop:12}}><span className="tag">Channel check</span><span className="tag">Proof required</span></div><button className="primary" style={{marginTop:18}}>Open task</button></div></main>}
function Ads(){return <main className="content"><section className="card empty" style={{minHeight:420}}><div className="empty-icon"><Play size={54}/></div><h2>Watch an ad</h2><p>Each completed ad counts as a valid ad view. Valid ad views unlock your referrers' pending commission.</p><button className="primary">◉&nbsp; Watch ad</button></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>✧ Valid ad views</h2><b style={{fontSize:36}}>4</b></div><div className="sub" style={{fontSize:18}}>Referral unlock progress <span style={{float:'right'}}>4/5</span></div><div style={{height:14,background:'#172a23',borderRadius:20,marginTop:10,overflow:'hidden'}}><div style={{width:'80%',height:'100%',background:'#2bbd78'}}/></div><p className="sub" style={{fontSize:16,marginBottom:0}}>Once you complete 5 valid ad views, your referrer's accumulated 20% commission is released to their wallet.</p></section></main>}
function WalletPage(){return <main className="content"><div className="stats"><Stat v="$0.00" l="Best day"/><Stat v="0" l="Tasks completed"/><Stat v="$0.00" l="Referral earnings"/><Stat v="$0.00" l="Total withdrawals"/></div><section className="card" style={{marginTop:22}}><div className="pills">{['Earnings','Balance','Tasks','Referrals'].map((x,i)=><button className={'pill '+(i===0?'active':'')} key={x}>{x}</button>)}</div><div className="pills" style={{marginTop:14}}>{['1D','7D','30D','3M','6M','1Y','All'].map((x,i)=><button className={'pill '+(i===1?'active':'')} key={x}>{x}</button>)}</div><div style={{marginTop:22}} className="chart"><div className="line"/></div></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>Withdraw</h2></div><div className="sub" style={{fontSize:17}}>Minimums are controlled by the administrator. Bank withdrawals are available only for Nigerian banks and apply the configured 10% fee.</div><button className="primary" style={{marginTop:18}}>Request withdrawal</button></section></main>}
function Community(){return <main className="content"><div className="section-head"><h2>Community</h2><button className="primary" style={{fontSize:16,padding:'12px 16px'}}><Plus size={18}/> New post</button></div><section className="card"><div className="notice"><Shield size={22}/> Hashtag/spam moderation can delete matching posts and apply the configured balance penalty.</div><div className="task-card" style={{marginTop:16}}><div className="sub" style={{fontSize:16}}>HillsByte Admin</div><h3>Welcome to the HillsByte community</h3><p className="sub" style={{fontSize:17}}>Ask questions, share opinions and help other members. Media posting is restricted until the withdrawal requirement is met; admin posts can include pictures and videos.</p><div className="task-meta"><span className="tag">12 comments</span><span className="tag">2h ago</span></div></div></section></main>}
function Profile(){return <main className="content"><section className="card"><div style={{display:'flex',gap:20,alignItems:'center'}}><div className="avatar" style={{width:82,height:82,fontSize:34}}>H</div><div><h2 style={{margin:0,fontSize:28}}>HillsByte</h2><div className="sub" style={{fontSize:16}}>Telegram: @hillsbyte • ID: protected</div></div><button className="pill" style={{marginLeft:'auto'}}><Edit size={18}/> Edit</button></div></section><div className="stats"><Stat v="100" l="Trust score"/><Stat v="30 XP" l="Experience"/><Stat v="3 days" l="Streak"/><Stat v="2" l="HillsCoin"/></div><section className="card" style={{marginTop:22}}><div className="section-head"><h2 style={{fontSize:24}}>Activity</h2></div><div className="chart"><div className="line"/></div></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>Event calendar</h2><Calendar size={26}/></div><p className="sub" style={{fontSize:17}}>No active event participation.</p></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>Redeem code</h2></div><div className="row2"><input placeholder="Enter code" style={{background:'#10221c',border:'1px solid #1b3a30',color:'white',borderRadius:18,padding:15}}/><button className="primary">Redeem</button></div></section></main>}
function Leaderboard(){return <main className="content"><h1 style={{fontSize:34,margin:'0 0 8px'}}>Leaderboards</h1><div className="sub">See how you rank across HillsByte.</div><div className="pills" style={{marginTop:38}}>{['🏆 Top Earners','♧ Top Referrers','◉ Most Tasks'].map((x,i)=><button className={'pill '+(i===0?'active':'')} key={x}>{x}</button>)}</div><div className="pills" style={{marginTop:18}}>{['Today','This Week','This Month','All Time'].map((x,i)=><button className={'pill '+(i===3?'active':'')} key={x}>{x}</button>)}</div><section className="card empty" style={{minHeight:610}}><div className="empty-icon"><Trophy size={54}/></div><h2>No rankings yet</h2><p>Be the first to climb the leaderboard.</p></section></main>}
function ActivityPage(){return <main className="content"><div className="section-head"><h2>Activity</h2><span className="link">All</span></div><section className="card"><div className="sub">No activity yet.</div></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>Earnings over time</h2></div><div className="chart"><div className="line" style={{transform:'none',bottom:'18%',height:0}}/></div></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>User growth</h2></div><div className="chart"><div className="line"/></div></section><section className="card"><div className="section-head"><h2 style={{fontSize:24}}>Top tasks by submissions</h2></div><div className="barwrap"><div className="bar" style={{height:'45%'}}/><div className="bar" style={{height:'70%'}}/></div></section></main>}
function Referrals(){return <main className="content"><div className="section-head"><h2>Referrals</h2></div><section className="card"><div className="stats"><Stat v="0" l="Total referrals"/><Stat v="$0.00" l="Commission"/><Stat v="$0.00" l="Event earnings"/><Stat v="0" l="Pending referrals"/></div></section><section className="card"><h2 style={{fontSize:24}}>Team growth</h2><div className="chart" style={{marginTop:20}}><div className="line"/></div></section><section className="card"><h2 style={{fontSize:24}}>Requirements</h2><p className="sub" style={{fontSize:17}}>The administrator can require any combination of: join the channel, complete 4 tasks, reach 50 XP, or make the first withdrawal.</p></section></main>}
function Events(){return <main className="content"><div className="section-head"><h2>Events</h2></div><section className="card"><div style={{height:170,borderRadius:24,background:'radial-gradient(circle at 40% 40%,#1e9c68,#09251b 55%,#07130f)',display:'grid',placeItems:'center'}}><Coin size={76}/></div><h2>Referral Challenge</h2><p className="sub" style={{fontSize:17}}>Top referrers this week receive bonus rewards. Climb the leaderboard!</p><button className="primary">View event</button></section><section className="card"><h2 style={{fontSize:24}}>Event calendar</h2><p className="sub" style={{fontSize:17}}>No other events are currently running.</p></section></main>}
function Assistant(){return <main className="content"><section className="card empty" style={{minHeight:540}}><div className="empty-icon"><Bot size={54}/></div><h2>HillsByte Assistant</h2><p>Ask how to find tasks, submit proof, understand XP and trust, withdraw, use referrals or participate in events.</p><div style={{width:'100%',maxWidth:500,display:'grid',gap:10}}>{['How do I submit task proof?','How does the trust score work?','How do I withdraw?'].map(q=><button className="pill" key={q}>{q}</button>)}</div></section></main>}
function Admin(){const stats=[['$0.00','Revenue'],['$0.00','Pending revenue'],['$0.00','Referral commissions'],['$0.00','Referral earnings'],['0','Events completed'],['0','Events running'],['6','Total users'],['0','Tasks completed'],['6','User growth'],['0','Pending referrals'],['0','Pending withdrawals'],['$0.00','Withdrawals paid'],['0','Ads watched'],['0','HillsCoin earned'],['0','Community activity']];return <main className="content"><div className="section-head"><div><h2>Admin Control Center</h2><div className="sub" style={{fontSize:16}}>Overview, users, tasks, events, withdrawals and settings.</div></div></div><div className="admin-tabs">{['Overview','Users','Tasks','Proof review','Withdrawals','Events','Announcements','Referrals','Community','Settings'].map((x,i)=><button className={'pill '+(i===0?'active':'')} key={x}>{x}</button>)}</div><div style={{height:18}}/><div className="stats">{stats.map(([v,l])=><Stat v={v} l={l} key={l}/>)}</div><section className="card" style={{marginTop:22}}><div className="section-head"><h2 style={{fontSize:24}}>Growth performance</h2><span className="link">09-12 → 09-26</span></div><div className="chart"><div className="line"/></div></section><section className="card"><h2 style={{fontSize:24}}>User management</h2><div className="table" style={{marginTop:16}}><table><thead><tr><th>Telegram user</th><th>ID</th><th>Status</th><th>Trust</th><th>Actions</th></tr></thead><tbody><tr><td>@hillsbyte</td><td>••••••</td><td className="success">active</td><td>100</td><td><button className="pill">View</button></td></tr><tr><td>@newuser</td><td>••••••</td><td>active</td><td>98</td><td><button className="pill">Message</button></td></tr></tbody></table></div></section><section className="card"><h2 style={{fontSize:24}}>Proof review</h2><div className="task-card"><h3>Write a short review</h3><div className="sub" style={{fontSize:16}}>Submitted by @user • pending</div><div style={{display:'flex',gap:10,marginTop:14}}><button className="primary">Approve</button><button className="pill">Reject</button></div></div></section><section className="card"><h2 style={{fontSize:24}}>Wallet & withdrawal settings</h2><div className="row2"><div className="field"><label>Minimum USDT withdrawal</label><input defaultValue="1.00"/></div><div className="field"><label>USD → NGN rate</label><input defaultValue="1500"/></div></div><div className="row2" style={{marginTop:16}}><div className="field"><label>Bank withdrawal fee %</label><input defaultValue="10"/></div><div className="field"><label>Default task XP</label><input defaultValue="10"/></div></div><button className="primary" style={{marginTop:18}}>Save settings</button></section></main>}
function Stat({v,l}:{v:string;l:string}){return <div className="stat"><b>{v}</b><span>{l}</span></div>}
function Bottom({active,setScreen}:{active:Screen;setScreen:(s:Screen)=>void}){return <nav className="bottom">{([['earn','Earn',Spark],['ads','Ads',Play],['wallet','Wallet',Wallet],['community','Community',Users],['profile','Profile',User]] as [Screen,string,React.ComponentType<any>][]).map(([s,l,I])=><button key={s} className={active===s?'active':''} onClick={()=>setScreen(s)}><I size={31}/><span>{l}</span></button>)}</nav>}
function Drawer({active,close,setScreen,admin,setAdmin}:{active:Screen;close:()=>void;setScreen:(s:Screen)=>void;admin:boolean;setAdmin:(b:boolean)=>void}){return <div className="drawerShade" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerTop"><div className="avatar">H</div><strong>HillsByte</strong><button className="drawerClose" onClick={close}><X size={30}/></button></div>{nav.map(([s,l,I])=><button key={s} className={'drawerItem '+(active===s?'active':'')} onClick={()=>{setScreen(s);close()}}><I size={28}/>{l}</button>)}<button className={'drawerItem '+(admin?'active':'')} onClick={()=>{setAdmin(true);setScreen('admin');close()}}><Shield size={28}/>Admin</button></aside></div>}
function Modal({kind,close}:{kind:string;close:()=>void}){return <div className="modalShade" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}>{kind==='checkin'?<><h2>Daily check-in</h2><p className="sub">Your check-in streak is controlled by the administrator. Completing day 7 activates a 2% task reward bonus.</p><button className="primary" onClick={close}>Check in</button></>:<><div style={{display:'flex',justifyContent:'space-between'}}><h2>Referral Challenge</h2><button className="drawerClose" onClick={close}><X size={26}/></button></div><div className="formgrid"><div className="field"><label>Title</label><input defaultValue="Referral Challenge"/></div><div className="field"><label>Description</label><textarea defaultValue="Top referrers this week receive bonus rewards. Climb the leaderboard!"/></div><div className="field"><label>Banner URL</label><input placeholder="Leave empty to use 3D banner"/></div><label style={{display:'flex',gap:10,alignItems:'center',fontSize:18}}><input type="checkbox" defaultChecked/> Use animated 3D banner</label><div className="field"><label>Reward</label><input defaultValue="Bonus for top 10 referrers"/></div><div className="field"><label>Rules</label><textarea/></div><div className="row2"><div className="field"><label>Start</label><input type="datetime-local"/></div><div className="field"><label>End</label><input type="datetime-local"/></div></div><div className="row2"><div className="field"><label>CTA label</label><input defaultValue="Invite friends"/></div><div className="field"><label>CTA URL</label><input defaultValue="/referral"/></div></div><button className="primary" onClick={close}>Save event</button></div></>}</div></div>}
