'use client';
import {useEffect,useMemo,useState} from 'react';

const currencies={USD:{name:'US Dollar',symbol:'$',rate:1},NGN:{name:'Nigerian Naira',symbol:'₦',rate:1600},EUR:{name:'Euro',symbol:'€',rate:.86},GBP:{name:'British Pound',symbol:'£',rate:.74},GHS:{name:'Ghanaian Cedi',symbol:'₵',rate:15.2},KES:{name:'Kenyan Shilling',symbol:'KSh',rate:129},ZAR:{name:'South African Rand',symbol:'R',rate:17.4},CAD:{name:'Canadian Dollar',symbol:'C$',rate:1.38},AUD:{name:'Australian Dollar',symbol:'A$',rate:1.52},INR:{name:'Indian Rupee',symbol:'₹',rate:88},JPY:{name:'Japanese Yen',symbol:'¥',rate:147},TRY:{name:'Turkish Lira',symbol:'₺',rate:41},AED:{name:'UAE Dirham',symbol:'د.إ',rate:3.67},SAR:{name:'Saudi Riyal',symbol:'﷼',rate:3.75},USDT:{name:'Tether',symbol:'₮',rate:1}};
const tasks=[['Write a short review','content',.12],['Daily check-in bonus','daily',.02],['Try a partner app','apps',.15],['Follow HillsByte on X','social',.05],['Join HillsByte Community','telegram',.07]];
const adminTabs=['Dashboard','Overview','Analytics','Tasks','Proofs','Withdrawals','Payouts','Ads','Events','Announcements','Referral','Users','Reviewers','Permissions','Moderation','Telegram','Redeem Codes'];
const userTabs=['Home','Earn','Wallet','Activity','Referrals','Community','Events','Leaderboard','Notifications','Profile'];
function Icon({children}){return <span className="ico">{children}</span>}
function Money({amount,currency}){const c=currencies[currency];return <>{c.symbol}{(amount*c.rate).toFixed(currency==='NGN'?0:2)}</>}
export default function App(){
 const [view,setView]=useState('Home'); const [admin,setAdmin]=useState(false); const [currency,setCurrency]=useState(()=>typeof window==='undefined'?'USD':localStorage.getItem('hb_currency')||'USD');
 const [balance]=useState(0); const [hbc]=useState(25); const [menu,setMenu]=useState(false); const [toast,setToast]=useState(''); const [tg,setTg]=useState(null); const [payouts,setPayouts]=useState({bank:{min:5,fee:0.5,type:'percent'},trc:{min:2,fee:.2,type:'fixed'},ton:{min:2,fee:.2,type:'fixed'}}); const [ref,setRef]=useState({commission:20,minAds:5,pendingDays:7,minTasks:1});
 useEffect(()=>{localStorage.setItem('hb_currency',currency)},[currency]);
 useEffect(()=>{if(typeof window!=='undefined'){const u=window.Telegram?.WebApp; if(u){u.ready();setTg(u.initDataUnsafe?.user||null)}}},[]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const display=useMemo(()=>currencies[currency], [currency]);
 const selectView=v=>{setView(v);setAdmin(false);setMenu(false)};
 const adminView=v=>{setView(v);setAdmin(true);setMenu(false)};
 return <div className="app">
  <header className="top"><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button><div className="brand"><b>H</b><strong>HillsByte</strong></div><button className="bell">♧<i>1</i></button></header>
  {menu&&<aside className="drawer"><div className="drawerHead"><div className="brand"><b>H</b><strong>HillsByte</strong></div><button onClick={()=>setMenu(false)}>×</button></div>{userTabs.map(x=><button key={x} className={view===x&&!admin?'active':''} onClick={()=>selectView(x)}>{x}</button>)}<hr/><button onClick={()=>adminView('Dashboard')}>⚿ Admin</button></aside>}
  <main className="content">{admin?<Admin tab={view} payouts={payouts} setPayouts={setPayouts} refCfg={ref} setRef={setRef} notify={notify}/>:<User view={view} currency={currency} setCurrency={setCurrency} balance={balance} hbc={hbc} display={display} tg={tg} notify={notify}/>}</main>
  {toast&&<div className="toast">{toast}</div>}
  <nav className="bottom">{['Earn','Wallet','Community','Profile'].map(x=><button key={x} onClick={()=>selectView(x)} className={view===x?'sel':''}><Icon>{x==='Earn'?'✧':x==='Wallet'?'▣':x==='Community'?'♧':'♙'}</Icon>{x}</button>)}</nav>
 </div>
}
function Header({title,sub}){return <><div className="pageTitle"><h1>{title}</h1>{sub&&<p>{sub}</p>}</div></>}
function Cards({currency,balance,hbc}){return <div className="cards"><Card label="Available Balance"><Money amount={balance} currency={currency}/></Card><Card label="Pending"><Money amount={0} currency={currency}/></Card><Card label="Lifetime Earnings"><Money amount={0} currency={currency}/></Card><Card label="Referral earnings"><Money amount={0} currency={currency}/></Card><Card label="Withdrawable"><Money amount={0} currency={currency}/></Card><Card label="HillsCoin">{hbc} HBC</Card></div>}
function Card({label,children}){return <div className="card"><small>{label}</small><strong>{children}</strong></div>}
function User({view,currency,setCurrency,balance,hbc,display,tg,notify}){
 if(view==='Profile')return <><Header title="Profile"/><div className="profile card"><div className="avatar">{tg?.first_name?.[0]||'Z'}</div><div><h2>{tg?.first_name||'Zoomey Canary'}</h2><p>{tg?`@${tg.username||'telegram_user'}`:'Telegram account'}</p><span className="tag">Admin</span></div></div><Cards currency={currency} balance={balance} hbc={hbc}/><h3>⚙ Settings</h3><div className="settings card"><label>Display currency<select value={currency} onChange={e=>setCurrency(e.target.value)}>{Object.entries(currencies).map(([k,v])=><option key={k} value={k}>{k} — {v.name}</option>)}</select></label><label>Language<select><option>English</option></select></label><label>Notifications<span>On</span></label><label>Privacy<span>Default</span></label><label>Telegram<span className="ok">✓ Connected</span></label></div><button className="danger wide">↪ Sign out</button></>;
 if(view==='Wallet')return <><Header title="Wallet" sub="Your balances, transactions and withdrawals."/><Cards currency={currency} balance={balance} hbc={hbc}/><button className="primary wide" onClick={()=>notify('Withdrawal settings are controlled by the admin.')}>⇩ Withdraw</button><section className="section"><h3>Transaction history</h3><Empty text="No transactions yet" sub="Your earnings will appear here."/></section></>;
 if(view==='Earn')return <><Header title="Earn More" sub="Complete tasks and turn your activity into rewards."/><input className="search" placeholder="⌕ Search tasks..."/><div className="chips"><b>All</b><span>Social</span><span>Telegram</span><span>Community</span><span>Apps</span></div><div className="taskList">{tasks.map(t=><div className="task card" key={t[0]}><div><small>{t[1]}</small><h3>{t[0]}</h3><p>Proof may be required after completion.</p></div><strong><Money amount={t[2]} currency={currency}/></strong></div>)}</div></>;
 if(view==='Community')return <><Header title="Community" sub="Connect with the HillsByte community. Posts auto-expire after 2 days."/><div className="postBox card"><textarea placeholder="Share something with the community..."></textarea><button className="primary" onClick={()=>notify('Post published')}>➤ Post</button></div>{['Fuck you','Which country are you all from?'].map((p,i)=><div className="post card" key={i}><b>Zoomey Canary <span className="tag">ADMIN</span></b><small>1h ago</small><p>{p}</p><span>♡ 0 Reply</span></div>)}</>;
 if(view==='Activity')return <><Header title="Activity" sub="Your HillsByte account activity — not financial trading."/><Cards currency={currency} balance={balance} hbc={hbc}/><div className="chart card"><div className="chips"><b>Earnings</b><span>Balance</span><span>Tasks</span><span>Referrals</span><span>Withdrawals</span></div><div className="fakechart">╲╱╲╱╲╱╲╱</div></div><Empty text="No activity yet" sub="Complete tasks to see your earnings chart grow."/></>;
 if(view==='Referrals')return <><Header title="Referrals" sub="Invite friends and earn configured commissions."/><div className="hero card"><h2>20% referral commission</h2><p>Commission remains pending until the configured qualification requirements are met.</p><div className="code">HB-DEMO <button onClick={()=>notify('Referral code copied')}>Copy</button></div></div><Cards currency={currency} balance={0} hbc={hbc}/></>;
 if(view==='Leaderboard')return <><Header title="Leaderboards" sub="See how you rank across HillsByte."/><div className="chips"><b>Top Earners</b><span>Top Referrers</span><span>Most Tasks</span><span>Longest Streak</span></div><div className="chips"><span>Today</span><span>This Week</span><span>This Month</span><b>All Time</b></div><Empty text="No rankings yet" sub="Be the first to climb the leaderboard."/></>;
 if(view==='Events')return <><Header title="Events"/><Empty text="No events yet" sub="New HillsByte events will appear here."/></>;
 if(view==='Notifications')return <><Header title="Notifications"/><Empty text="You're all caught up" sub="No new notifications."/></>;
 return <><Header title={tg?`Welcome back, ${tg.first_name||'Zoomey Canary'}`:'Welcome back, Zoomey Canary'} sub="Here's your HillsByte snapshot."/><Cards currency={currency} balance={balance} hbc={hbc}/><div className="check card"><b>🔥 Daily check-in</b><small>Current streak: 1 day</small><button className="primary" onClick={()=>notify('Daily check-in claimed')}>Check in</button><div className="days">{['D1','D2','D3','D4','D5','D6','D7'].map((d,i)=><span className={i===0?'on':''} key={d}>{d}</span>)}</div></div><h3>Quick actions</h3><div className="quick">{['Earn','Wallet','Referral','Activity','Community','Events','Leaderboard','Profile'].map(x=><button key={x} onClick={()=>{}}><i>{x==='Wallet'?'▣':x==='Referral'?'♧':x==='Activity'?'⌁':x==='Events'?'▦':x==='Leaderboard'?'♜':x==='Profile'?'♙':'✧'}</i>{x}</button>)}</div><Empty text="No earnings yet" sub="Complete your first task to start earning."/></>;
}
function Empty({text,sub}){return <div className="empty"><div>⌁</div><b>{text}</b><p>{sub}</p><button className="primary">Find tasks</button></div>}
function Admin({tab,payouts,setPayouts,refCfg,setRef,notify}){
 const [modal,setModal]=useState(null); const save=()=>{setModal(null);notify('Settings saved successfully')};
 if(tab==='Dashboard'||tab==='Overview')return <><Header title="⚿ Admin Control Center"/><AdminNav active={tab}/><div className="growth"><h2>⌁ Growth dashboard <select><option>14 days</option><option>30 days</option></select></h2><div className="cards"><Card label="Earnings">$0.33</Card><Card label="Active users">9</Card><Card label="Tasks completed">4</Card><Card label="Ad views">7</Card><Card label="Withdrawals">$0.12</Card><Card label="Active referrals">0</Card></div><div className="chart card"><h3>Revenue vs referral commissions</h3><div className="fakechart big">╱╲╱╲╱╲╱╲╱</div></div></div></>;
 if(tab==='Payouts'||tab==='Withdrawals')return <><Header title="⚿ Admin Control Center"/><AdminNav active={tab}/><div className="adminPanel card"><h2>Withdrawal configuration</h2><p>Set minimum withdrawal and fee independently for every payout method.</p>{[['bank','Bank (NGN)'],['trc','USDT TRC20'],['ton','TON']].map(([k,n])=><div className="method" key={k}><h3>{n}</h3><label>Minimum withdrawal<input type="number" value={payouts[k].min} onChange={e=>setPayouts({...payouts,[k]:{...payouts[k],min:+e.target.value}})}/></label><label>Fee<input type="number" value={payouts[k].fee} onChange={e=>setPayouts({...payouts,[k]:{...payouts[k],fee:+e.target.value}})}/></label><select value={payouts[k].type} onChange={e=>setPayouts({...payouts,[k]:{...payouts[k],type:e.target.value}})}><option value="fixed">Fixed fee</option><option value="percent">Percentage fee</option></select></div>)}<button className="primary" onClick={()=>notify('Payout configuration saved')}>▣ Save payout settings</button></div></>;
 if(tab==='Referral')return <><Header title="⚿ Admin Control Center"/><AdminNav active="Referral"/><div className="adminPanel card"><h2>Referral configuration</h2><label>Commission percentage<input type="number" value={refCfg.commission} onChange={e=>setRef({...refCfg,commission:+e.target.value})}/></label><label>Minimum valid ad views<input type="number" value={refCfg.minAds} onChange={e=>setRef({...refCfg,minAds:+e.target.value})}/></label><label>Minimum completed tasks<input type="number" value={refCfg.minTasks} onChange={e=>setRef({...refCfg,minTasks:+e.target.value})}/></label><label>Pending period (days)<input type="number" value={refCfg.pendingDays} onChange={e=>setRef({...refCfg,pendingDays:+e.target.value})}/></label><button className="primary" onClick={()=>notify('Referral settings saved')}>▣ Save referral settings</button></div></>;
 if(tab==='Permissions'||tab==='Reviewers')return <><Header title="⚿ Admin Control Center"/><AdminNav active={tab}/><div className="adminPanel card"><h2>{tab==='Permissions'?'Permissions':'Reviewers'}</h2><p>Assign granular access instead of giving every staff member full admin access.</p>{['Manage tasks','Review proofs','Approve withdrawals','Manage users','Manage referrals','Moderate community','Manage announcements','Manage Telegram'].map((x,i)=><div className="permission"><span>{x}</span><input type="checkbox" defaultChecked={i<3}/></div>)}<button className="primary" onClick={save}>▣ Save permissions</button></div></>;
 if(tab==='Moderation')return <><Header title="⚿ Admin Control Center"/><AdminNav active="Moderation"/><div className="adminPanel card"><h2>Community moderation</h2><label><input type="checkbox" defaultChecked/> Enable banned-word filter</label><label>Banned words<textarea defaultValue={'Fuck\nSpam\nScam'} /></label><label>Penalty per violation<input type="number" defaultValue="0.03"/></label><button className="primary" onClick={save}>▣ Save moderation settings</button></div></>;
 if(tab==='Telegram')return <><Header title="⚿ Admin Control Center"/><AdminNav active="Telegram"/><div className="adminPanel card"><h2>Telegram settings</h2><p>The bot username is auto-discovered from Telegram getMe — no manual entry needed when the secret is configured.</p><label>Bot token<input placeholder="123456:ABC-DEF..." type="password"/></label><label>Channel ID<input placeholder="-100434689962"/></label><label>Channel username<input placeholder="@HillsByte"/></label><label><input type="checkbox" defaultChecked/> Require channel membership</label><button className="primary" onClick={save}>▣ Save & apply Telegram settings</button></div></>;
 if(tab==='Ads')return <AdminGeneric title="Ads" fields={['Ad provider','Reward per eligible view','Daily view cap','Minimum seconds','Enable ads']}/>;
 if(tab==='Events')return <AdminGeneric title="Events" fields={['Title','Description','Banner URL','Reward','Rules','Start','End','CTA label','CTA URL']}/>;
 if(tab==='Announcements')return <AdminGeneric title="Announcements" fields={['Title','Message','Broadcast to Telegram']}/>;
 if(tab==='Redeem Codes')return <AdminGeneric title="Redeem codes" fields={['Amount (USD)','Capacity (users)','Note']}/>;
 if(tab==='Users')return <AdminGeneric title="Users" fields={['Search by name, email or Telegram username','Status','Role']}/>;
 if(tab==='Proofs')return <AdminGeneric title="Proof review" fields={['Search submissions','Status','Reviewer','Decision']}/>;
 if(tab==='Analytics')return <><Header title="⚿ Admin Control Center"/><AdminNav active="Analytics"/><div className="chart card"><h2>Revenue vs referral commissions</h2><div className="fakechart big">╲╱╱╲╱╲╲╱╱╲╱</div></div><div className="chart card"><h2>User growth</h2><div className="fakechart big">╱╱╱╱╱╱</div></div></>;
 return <AdminGeneric title="Tasks" fields={['Title','Description','Reward (USD)','Category','Est. minutes','Difficulty','Max slots','Timer (sec)','Task URL','Logo URL','Instructions','Requirements','Proof required']}/>;
}
function AdminNav({active}){return <div className="adminNav">{adminTabs.map(x=><button className={x===active?'active':''} key={x} onClick={()=>{location.href='/admin?tab='+encodeURIComponent(x)}}>{x}</button>)}</div>}
function AdminGeneric({title,fields}){return <><Header title="⚿ Admin Control Center"/><AdminNav active={title}/><div className="adminPanel card"><h2>{title}</h2><button className="primary" onClick={()=>alert(title+' saved')}>＋ New {title==='Tasks'?'task':title==='Events'?'event':title==='Redeem Codes'?'redeem code':'item'}</button><div className="formgrid">{fields.map(f=><label key={f}>{f}<input placeholder={f}/></label>)}</div><button className="primary wide">▣ Save</button></div></>}
